-- ============================================================================
-- RUMI Manager v5.5 — SECURITY & SMART ATTENDANCE
-- Chạy SAU: V4 FULL -> V5.3 OPERATIONS -> V5.4 SHIFT MARKET.
-- Chỉ tạo/sửa đối tượng có tiền tố rumi_, không đụng dữ liệu IC3 Smart Class.
-- ============================================================================

begin;

-- --------------------------------------------------------------------------
-- 1) Bảo mật tài khoản và phiên đăng nhập có thể thu hồi
-- --------------------------------------------------------------------------
alter table public.rumi_users add column if not exists password_iterations integer not null default 210000;
alter table public.rumi_users add column if not exists must_change_password boolean not null default false;
alter table public.rumi_users add column if not exists password_changed_at timestamptz;
alter table public.rumi_users add column if not exists failed_login_count integer not null default 0;
alter table public.rumi_users add column if not exists locked_until timestamptz;
alter table public.rumi_users add column if not exists last_failed_login_at timestamptz;
alter table public.rumi_users add column if not exists last_login_ip_hash text not null default '';
alter table public.rumi_users add column if not exists last_login_user_agent_hash text not null default '';

alter table public.rumi_users drop constraint if exists rumi_users_password_iterations_check;
alter table public.rumi_users add constraint rumi_users_password_iterations_check
  check (password_iterations between 100000 and 2000000);
alter table public.rumi_users drop constraint if exists rumi_users_failed_login_check;
alter table public.rumi_users add constraint rumi_users_failed_login_check
  check (failed_login_count between 0 and 1000);

create table if not exists public.rumi_auth_sessions (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.rumi_users(id) on delete cascade,
  token_hash text not null unique,
  user_agent_hash text not null default '',
  ip_hash text not null default '',
  device_label text not null default '',
  created_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  idle_expires_at timestamptz not null,
  expires_at timestamptz not null,
  revoked_at timestamptz,
  revoke_reason text not null default ''
);
create index if not exists rumi_auth_sessions_user_active_idx
  on public.rumi_auth_sessions(user_id, revoked_at, expires_at desc);
create index if not exists rumi_auth_sessions_token_idx
  on public.rumi_auth_sessions(token_hash);

create table if not exists public.rumi_password_history (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.rumi_users(id) on delete cascade,
  password_hash text not null,
  password_salt text not null,
  password_iterations integer not null,
  created_at timestamptz not null default now()
);
create index if not exists rumi_password_history_user_idx
  on public.rumi_password_history(user_id, created_at desc);

create table if not exists public.rumi_login_throttles (
  key_hash text primary key,
  attempts integer not null default 0,
  first_attempt_at timestamptz not null default now(),
  last_attempt_at timestamptz not null default now(),
  locked_until timestamptz
);
create index if not exists rumi_login_throttles_lock_idx
  on public.rumi_login_throttles(locked_until);

create or replace function public.rumi_auth_register_failure(
  p_key_hash text,
  p_user_id bigint default null,
  p_now timestamptz default now()
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_row public.rumi_login_throttles%rowtype;
  v_attempts integer;
  v_lock_minutes integer := 0;
begin
  insert into public.rumi_login_throttles(key_hash, attempts, first_attempt_at, last_attempt_at)
  values (p_key_hash, 1, p_now, p_now)
  on conflict (key_hash) do update set
    attempts = case
      when public.rumi_login_throttles.first_attempt_at < p_now - interval '10 minutes' then 1
      else public.rumi_login_throttles.attempts + 1
    end,
    first_attempt_at = case
      when public.rumi_login_throttles.first_attempt_at < p_now - interval '10 minutes' then p_now
      else public.rumi_login_throttles.first_attempt_at
    end,
    last_attempt_at = p_now,
    locked_until = case
      when (case when public.rumi_login_throttles.first_attempt_at < p_now - interval '10 minutes' then 1 else public.rumi_login_throttles.attempts + 1 end) >= 10 then p_now + interval '60 minutes'
      when (case when public.rumi_login_throttles.first_attempt_at < p_now - interval '10 minutes' then 1 else public.rumi_login_throttles.attempts + 1 end) >= 5 then p_now + interval '15 minutes'
      else null
    end
  returning * into v_row;

  v_attempts := v_row.attempts;
  if v_row.locked_until is not null then
    v_lock_minutes := greatest(1, ceil(extract(epoch from (v_row.locked_until - p_now)) / 60)::integer);
  end if;

  if p_user_id is not null then
    update public.rumi_users
    set failed_login_count = least(failed_login_count + 1, 1000),
        last_failed_login_at = p_now,
        locked_until = case
          when v_attempts >= 10 then p_now + interval '60 minutes'
          when v_attempts >= 5 then p_now + interval '15 minutes'
          else locked_until
        end
    where id = p_user_id;
  end if;

  return jsonb_build_object(
    'attempts', v_attempts,
    'locked', v_row.locked_until is not null and v_row.locked_until > p_now,
    'locked_until', v_row.locked_until,
    'retry_after_minutes', v_lock_minutes
  );
end;
$$;

create or replace function public.rumi_auth_clear_failures(
  p_key_hash text,
  p_user_id bigint default null,
  p_now timestamptz default now()
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  delete from public.rumi_login_throttles where key_hash = p_key_hash;
  if p_user_id is not null then
    update public.rumi_users
    set failed_login_count = 0,
        locked_until = null,
        last_failed_login_at = null
    where id = p_user_id;
  end if;
end;
$$;

-- --------------------------------------------------------------------------
-- 2) Quy định chấm công thông minh
-- --------------------------------------------------------------------------
alter table public.rumi_settings add column if not exists late_grace_minutes integer not null default 5;
alter table public.rumi_settings add column if not exists early_leave_grace_minutes integer not null default 5;
alter table public.rumi_settings add column if not exists max_overtime_minutes integer not null default 180;
alter table public.rumi_settings add column if not exists overtime_requires_approval boolean not null default true;
alter table public.rumi_settings add column if not exists location_freshness_seconds integer not null default 120;
alter table public.rumi_settings add column if not exists min_clock_gap_minutes integer not null default 1;

alter table public.rumi_settings drop constraint if exists rumi_settings_smart_attendance_check;
alter table public.rumi_settings add constraint rumi_settings_smart_attendance_check check (
  late_grace_minutes between 0 and 60 and
  early_leave_grace_minutes between 0 and 60 and
  max_overtime_minutes between 0 and 720 and
  location_freshness_seconds between 15 and 600 and
  min_clock_gap_minutes between 0 and 60
);

-- Giá trị mặc định thực tế hơn: cho phép ra ca muộn để ghi nhận tăng ca, nhưng tăng ca phải duyệt.
update public.rumi_settings
set checkout_after_minutes = 180
where id = 1 and checkout_after_minutes = 5;
update public.rumi_settings
set max_gps_accuracy_m = 80
where id = 1 and max_gps_accuracy_m = 150;

alter table public.rumi_attendance add column if not exists scheduled_minutes integer not null default 0;
alter table public.rumi_attendance add column if not exists worked_minutes integer not null default 0;
alter table public.rumi_attendance add column if not exists base_payable_minutes integer not null default 0;
alter table public.rumi_attendance add column if not exists payable_minutes integer not null default 0;
alter table public.rumi_attendance add column if not exists break_minutes integer not null default 0;
alter table public.rumi_attendance add column if not exists overtime_requested_minutes integer not null default 0;
alter table public.rumi_attendance add column if not exists overtime_approved_minutes integer not null default 0;
alter table public.rumi_attendance add column if not exists overtime_status text not null default 'Không có';
alter table public.rumi_attendance add column if not exists risk_level text not null default 'Thấp';
alter table public.rumi_attendance add column if not exists risk_reasons jsonb not null default '[]'::jsonb;
alter table public.rumi_attendance add column if not exists device_id_hash text not null default '';
alter table public.rumi_attendance add column if not exists client_position_at timestamptz;
alter table public.rumi_attendance add column if not exists review_status text not null default 'Không cần duyệt';
alter table public.rumi_attendance add column if not exists reviewed_at timestamptz;
alter table public.rumi_attendance add column if not exists reviewed_by bigint references public.rumi_users(id) on delete set null;

alter table public.rumi_attendance drop constraint if exists rumi_attendance_overtime_status_check;
alter table public.rumi_attendance add constraint rumi_attendance_overtime_status_check
  check (overtime_status in ('Không có','Chờ duyệt','Đã duyệt','Từ chối'));
alter table public.rumi_attendance drop constraint if exists rumi_attendance_risk_level_check;
alter table public.rumi_attendance add constraint rumi_attendance_risk_level_check
  check (risk_level in ('Thấp','Trung bình','Cao'));
alter table public.rumi_attendance drop constraint if exists rumi_attendance_review_status_check;
alter table public.rumi_attendance add constraint rumi_attendance_review_status_check
  check (review_status in ('Không cần duyệt','Chờ duyệt','Đã duyệt','Từ chối'));

-- Giữ nguyên tiền lương của dữ liệu cũ khi bổ sung các cột phút.
update public.rumi_attendance
set scheduled_minutes = case when scheduled_minutes = 0 then round(coalesce(scheduled_hours,0) * 60)::integer else scheduled_minutes end,
    worked_minutes = case when worked_minutes = 0 then round(coalesce(hours,0) * 60)::integer else worked_minutes end,
    payable_minutes = case when payable_minutes = 0 then round(coalesce(payable_hours,hours,0) * 60)::integer else payable_minutes end,
    base_payable_minutes = case when base_payable_minutes = 0 then greatest(0, round(coalesce(payable_hours,hours,0) * 60)::integer - coalesce(overtime_minutes,0)) else base_payable_minutes end,
    overtime_requested_minutes = case when overtime_requested_minutes = 0 then coalesce(overtime_minutes,0) else overtime_requested_minutes end,
    overtime_approved_minutes = case when overtime_approved_minutes = 0 then coalesce(overtime_minutes,0) else overtime_approved_minutes end,
    overtime_status = case when coalesce(overtime_minutes,0) > 0 and overtime_status = 'Không có' then 'Đã duyệt' else overtime_status end;

create table if not exists public.rumi_attendance_events (
  id bigint generated by default as identity primary key,
  shift_id bigint references public.rumi_shifts(id) on delete cascade,
  employee_id bigint references public.rumi_employees(id) on delete set null,
  action text not null,
  success boolean not null default false,
  reason text not null default '',
  latitude double precision,
  longitude double precision,
  accuracy_m double precision,
  distance_m double precision,
  device_id_hash text not null default '',
  ip_hash text not null default '',
  client_position_at timestamptz,
  created_at timestamptz not null default now()
);
create index if not exists rumi_attendance_events_shift_idx
  on public.rumi_attendance_events(shift_id, created_at desc);
create index if not exists rumi_attendance_events_employee_idx
  on public.rumi_attendance_events(employee_id, created_at desc);
create index if not exists rumi_attendance_events_device_idx
  on public.rumi_attendance_events(device_id_hash, created_at desc);

create table if not exists public.rumi_attendance_correction_requests (
  id bigint generated by default as identity primary key,
  attendance_id bigint references public.rumi_attendance(id) on delete cascade,
  shift_id bigint not null references public.rumi_shifts(id) on delete cascade,
  employee_id bigint not null references public.rumi_employees(id) on delete cascade,
  requested_check_in time without time zone,
  requested_check_out time without time zone,
  reason text not null,
  status text not null default 'Chờ duyệt'
    check (status in ('Chờ duyệt','Đã duyệt','Từ chối')),
  admin_note text not null default '',
  reviewed_by bigint references public.rumi_users(id) on delete set null,
  reviewed_at timestamptz,
  created_at timestamptz not null default now()
);
create index if not exists rumi_attendance_corrections_status_idx
  on public.rumi_attendance_correction_requests(status, created_at desc);
create unique index if not exists rumi_attendance_correction_pending_unique
  on public.rumi_attendance_correction_requests(shift_id, employee_id)
  where status = 'Chờ duyệt';

-- --------------------------------------------------------------------------
-- 3) Chấm công v5.5: giờ máy chủ là chuẩn; GPS phải mới, đủ chính xác và đúng cửa hàng.
--    Giờ vào sớm không cộng lương. Tăng ca chỉ cộng sau khi admin duyệt.
-- --------------------------------------------------------------------------
create or replace function public.rumi_clock_shift_v55(
  p_shift_id bigint,
  p_employee_id bigint,
  p_action text,
  p_lat double precision,
  p_lng double precision,
  p_accuracy double precision,
  p_device_hash text,
  p_client_time timestamptz,
  p_ip_hash text default '',
  p_now timestamptz default now()
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_shift public.rumi_shifts%rowtype;
  v_location public.rumi_locations%rowtype;
  v_settings public.rumi_settings%rowtype;
  v_att public.rumi_attendance%rowtype;
  v_shift_start timestamptz;
  v_shift_end timestamptz;
  v_distance double precision;
  v_action text;
  v_scheduled integer;
  v_worked integer;
  v_base integer;
  v_payable integer;
  v_late integer;
  v_early integer;
  v_ot integer;
  v_ot_approved integer;
  v_status text;
  v_risk text := 'Thấp';
  v_risks jsonb := '[]'::jsonb;
  v_shared_device boolean := false;
begin
  if p_lat is null or p_lng is null then raise exception 'Không nhận được vị trí GPS'; end if;
  if p_client_time is null then raise exception 'Vị trí GPS không có thời gian đo'; end if;

  select * into v_settings from public.rumi_settings where id = 1;
  if not found then raise exception 'Chưa cấu hình quy định chấm công'; end if;

  if abs(extract(epoch from (p_now - p_client_time))) > v_settings.location_freshness_seconds then
    raise exception 'Vị trí GPS đã cũ. Hãy bật vị trí chính xác và thử lại';
  end if;
  if p_accuracy is null or p_accuracy <= 0 or p_accuracy > v_settings.max_gps_accuracy_m then
    raise exception 'GPS chưa đủ chính xác. Sai số hiện tại % m, tối đa % m', round(coalesce(p_accuracy,9999)::numeric,0), v_settings.max_gps_accuracy_m;
  end if;

  select * into v_shift from public.rumi_shifts where id = p_shift_id for update;
  if not found then raise exception 'Không tìm thấy ca làm'; end if;
  if v_shift.employee_id <> p_employee_id then raise exception 'Ca làm không thuộc tài khoản này'; end if;
  if v_shift.status not in ('Đã xếp','Đã xác nhận') then raise exception 'Ca làm chưa được chốt để chấm công'; end if;
  if v_shift.location_id is null then raise exception 'Ca làm chưa được cấu hình vị trí cửa hàng'; end if;

  select * into v_location from public.rumi_locations where id = v_shift.location_id and active = true;
  if not found then raise exception 'Vị trí cửa hàng không tồn tại hoặc đã tắt'; end if;

  v_distance := 6371000 * 2 * asin(sqrt(
    power(sin(radians(p_lat - v_location.latitude) / 2), 2) +
    cos(radians(v_location.latitude)) * cos(radians(p_lat)) *
    power(sin(radians(p_lng - v_location.longitude) / 2), 2)
  ));
  if v_distance > v_location.radius_m then
    raise exception 'Bạn đang cách cửa hàng % m, phạm vi cho phép % m', round(v_distance::numeric,0), v_location.radius_m;
  end if;

  if p_accuracy > v_settings.max_gps_accuracy_m * 0.75 then
    v_risk := 'Trung bình';
    v_risks := v_risks || jsonb_build_array('Sai số GPS gần mức tối đa');
  end if;

  if coalesce(p_device_hash,'') <> '' then
    select exists(
      select 1 from public.rumi_attendance_events e
      where e.device_id_hash = p_device_hash
        and e.employee_id is distinct from p_employee_id
        and e.success = true
        and e.created_at > p_now - interval '30 minutes'
    ) into v_shared_device;
    if v_shared_device then
      v_risk := 'Cao';
      v_risks := v_risks || jsonb_build_array('Thiết bị vừa chấm công cho tài khoản khác');
    end if;
  end if;

  v_shift_start := (v_shift.shift_date + v_shift.start_time) at time zone v_settings.timezone;
  v_shift_end := (v_shift.shift_date + v_shift.end_time) at time zone v_settings.timezone;
  v_scheduled := greatest(0, floor(extract(epoch from (v_shift_end - v_shift_start)) / 60)::integer);

  select * into v_att from public.rumi_attendance where shift_id = p_shift_id for update;
  v_action := lower(coalesce(p_action,'auto'));
  if v_action = 'auto' then
    v_action := case when found and v_att.check_out_at is null then 'checkout' else 'checkin' end;
  end if;

  if v_action = 'checkin' then
    if found then raise exception 'Ca này đã chấm công vào'; end if;
    if p_now < v_shift_start - make_interval(mins => v_settings.checkin_before_minutes)
       or p_now > v_shift_start + make_interval(mins => v_settings.checkin_after_minutes) then
      raise exception 'Chỉ được chấm công vào từ % đến %',
        to_char(v_shift_start - make_interval(mins => v_settings.checkin_before_minutes),'HH24:MI'),
        to_char(v_shift_start + make_interval(mins => v_settings.checkin_after_minutes),'HH24:MI');
    end if;

    v_late := greatest(0, floor(extract(epoch from (p_now - v_shift_start)) / 60)::integer);
    insert into public.rumi_attendance(
      shift_id, employee_id, work_date, check_in, check_in_at,
      check_in_lat, check_in_lng, check_in_accuracy_m, check_in_distance_m,
      scheduled_minutes, scheduled_hours, late_minutes,
      status, note, device_id_hash, client_position_at, risk_level, risk_reasons,
      review_status
    ) values (
      p_shift_id, p_employee_id, v_shift.shift_date, (p_now at time zone v_settings.timezone)::time,
      p_now, p_lat, p_lng, p_accuracy, v_distance,
      v_scheduled, round(v_scheduled::numeric / 60, 2), v_late,
      case when v_late > v_settings.late_grace_minutes then 'Đi trễ' else 'Đang làm' end,
      '', coalesce(p_device_hash,''), p_client_time, v_risk, v_risks,
      case when v_risk = 'Cao' then 'Chờ duyệt' else 'Không cần duyệt' end
    ) returning * into v_att;

    insert into public.rumi_attendance_events(
      shift_id, employee_id, action, success, reason, latitude, longitude,
      accuracy_m, distance_m, device_id_hash, ip_hash, client_position_at
    ) values (
      p_shift_id, p_employee_id, 'checkin', true, '', p_lat, p_lng,
      p_accuracy, v_distance, coalesce(p_device_hash,''), coalesce(p_ip_hash,''), p_client_time
    );

    return jsonb_build_object(
      'attendance_id', v_att.id, 'action','checkin',
      'time',to_char(p_now at time zone v_settings.timezone,'HH24:MI'),
      'distance_m',round(v_distance::numeric,1), 'accuracy_m',round(p_accuracy::numeric,0),
      'late_minutes',v_late, 'risk_level',v_risk, 'review_status',v_att.review_status
    );
  end if;

  if v_action = 'checkout' then
    if not found then raise exception 'Bạn chưa chấm công vào ca này'; end if;
    if v_att.check_out_at is not null then raise exception 'Ca này đã chấm công ra'; end if;
    if p_now < v_shift_end - make_interval(mins => v_settings.checkout_before_minutes)
       or p_now > v_shift_end + make_interval(mins => v_settings.checkout_after_minutes) then
      raise exception 'Chỉ được chấm công ra từ % đến %',
        to_char(v_shift_end - make_interval(mins => v_settings.checkout_before_minutes),'HH24:MI'),
        to_char(v_shift_end + make_interval(mins => v_settings.checkout_after_minutes),'HH24:MI');
    end if;
    if p_now < v_att.check_in_at + make_interval(mins => v_settings.min_clock_gap_minutes) then
      raise exception 'Thời gian vào và ra ca quá gần nhau';
    end if;

    v_worked := greatest(0, floor(extract(epoch from (p_now - v_att.check_in_at)) / 60)::integer);
    v_late := greatest(0, floor(extract(epoch from (v_att.check_in_at - v_shift_start)) / 60)::integer);
    v_early := greatest(0, floor(extract(epoch from (v_shift_end - p_now)) / 60)::integer);
    v_ot := least(v_settings.max_overtime_minutes,
      greatest(0, floor(extract(epoch from (p_now - v_shift_end)) / 60)::integer));

    -- Chỉ trả lương trong khung ca. Vào sớm không làm tăng lương.
    v_base := greatest(0, floor(extract(epoch from (
      least(p_now, v_shift_end) - greatest(v_att.check_in_at, v_shift_start)
    )) / 60)::integer - coalesce(v_att.break_minutes,0));
    v_ot_approved := case when v_settings.overtime_requires_approval then 0 else v_ot end;
    v_payable := greatest(0, v_base + v_ot_approved);

    if v_ot > 0 and v_settings.overtime_requires_approval then
      v_status := 'Chờ duyệt tăng ca';
    elsif v_late > v_settings.late_grace_minutes and v_early > v_settings.early_leave_grace_minutes then
      v_status := 'Đi trễ & về sớm';
    elsif v_late > v_settings.late_grace_minutes then
      v_status := 'Đi trễ';
    elsif v_early > v_settings.early_leave_grace_minutes then
      v_status := 'Về sớm';
    elsif v_ot > 0 then
      v_status := 'Có tăng ca';
    else
      v_status := 'Hoàn thành';
    end if;

    update public.rumi_attendance set
      check_out = (p_now at time zone v_settings.timezone)::time,
      check_out_at = p_now,
      check_out_lat = p_lat,
      check_out_lng = p_lng,
      check_out_accuracy_m = p_accuracy,
      check_out_distance_m = v_distance,
      worked_minutes = v_worked,
      base_payable_minutes = v_base,
      payable_minutes = v_payable,
      overtime_requested_minutes = v_ot,
      overtime_approved_minutes = v_ot_approved,
      overtime_minutes = v_ot,
      overtime_status = case when v_ot = 0 then 'Không có' when v_settings.overtime_requires_approval then 'Chờ duyệt' else 'Đã duyệt' end,
      early_leave_minutes = v_early,
      late_minutes = v_late,
      hours = round(v_payable::numeric / 60, 2),
      payable_hours = round(v_payable::numeric / 60, 2),
      status = v_status,
      calculation_note = concat_ws(' · ',
        case when v_late > 0 then 'Trễ ' || v_late || ' phút' end,
        case when v_early > 0 then 'Về sớm ' || v_early || ' phút' end,
        case when v_ot > 0 then 'Tăng ca ' || v_ot || ' phút' end,
        'Tính lương ' || v_payable || ' phút'
      ),
      risk_level = case when v_risk = 'Cao' or risk_level = 'Cao' then 'Cao' when v_risk = 'Trung bình' or risk_level = 'Trung bình' then 'Trung bình' else 'Thấp' end,
      risk_reasons = risk_reasons || v_risks,
      review_status = case when v_risk = 'Cao' then 'Chờ duyệt' else review_status end,
      client_position_at = p_client_time
    where id = v_att.id
    returning * into v_att;

    insert into public.rumi_attendance_events(
      shift_id, employee_id, action, success, reason, latitude, longitude,
      accuracy_m, distance_m, device_id_hash, ip_hash, client_position_at
    ) values (
      p_shift_id, p_employee_id, 'checkout', true, '', p_lat, p_lng,
      p_accuracy, v_distance, coalesce(p_device_hash,''), coalesce(p_ip_hash,''), p_client_time
    );

    return jsonb_build_object(
      'attendance_id', v_att.id, 'action','checkout',
      'time',to_char(p_now at time zone v_settings.timezone,'HH24:MI'),
      'distance_m',round(v_distance::numeric,1), 'accuracy_m',round(p_accuracy::numeric,0),
      'worked_minutes',v_worked, 'base_payable_minutes',v_base,
      'overtime_requested_minutes',v_ot, 'overtime_approved_minutes',v_ot_approved,
      'payable_minutes',v_payable, 'hours',round(v_payable::numeric / 60, 2),
      'overtime_status',v_att.overtime_status, 'risk_level',v_att.risk_level,
      'review_status',v_att.review_status
    );
  end if;

  raise exception 'Hành động chấm công không hợp lệ';
end;
$$;

create or replace function public.rumi_review_overtime_v55(
  p_attendance_id bigint,
  p_approved_minutes integer,
  p_admin_user_id bigint,
  p_note text default ''
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_att public.rumi_attendance%rowtype;
  v_approved integer;
  v_payable integer;
begin
  select * into v_att from public.rumi_attendance where id = p_attendance_id for update;
  if not found then raise exception 'Không tìm thấy lượt chấm công'; end if;
  v_approved := greatest(0, least(coalesce(p_approved_minutes,0), coalesce(v_att.overtime_requested_minutes,0)));
  v_payable := greatest(0, coalesce(v_att.base_payable_minutes,0) + v_approved);
  update public.rumi_attendance set
    overtime_approved_minutes = v_approved,
    overtime_status = case when v_approved > 0 then 'Đã duyệt' else 'Từ chối' end,
    payable_minutes = v_payable,
    payable_hours = round(v_payable::numeric / 60,2),
    hours = round(v_payable::numeric / 60,2),
    review_status = 'Đã duyệt',
    reviewed_by = p_admin_user_id,
    reviewed_at = now(),
    note = case when coalesce(p_note,'') = '' then note else concat_ws(' · ', nullif(note,''), p_note) end,
    status = case
      when v_approved > 0 then 'Có tăng ca'
      when late_minutes > 0 and early_leave_minutes > 0 then 'Đi trễ & về sớm'
      when late_minutes > 0 then 'Đi trễ'
      when early_leave_minutes > 0 then 'Về sớm'
      else 'Hoàn thành'
    end
  where id = p_attendance_id
  returning * into v_att;
  return jsonb_build_object(
    'attendance_id',v_att.id,
    'approved_minutes',v_approved,
    'payable_minutes',v_payable,
    'payable_hours',round(v_payable::numeric / 60,2),
    'overtime_status',v_att.overtime_status
  );
end;
$$;

-- --------------------------------------------------------------------------
-- 4) RLS / quyền trực tiếp: trình duyệt không được truy cập các bảng bảo mật.
-- --------------------------------------------------------------------------
alter table public.rumi_auth_sessions enable row level security;
alter table public.rumi_password_history enable row level security;
alter table public.rumi_login_throttles enable row level security;
alter table public.rumi_attendance_events enable row level security;
alter table public.rumi_attendance_correction_requests enable row level security;

revoke all on table public.rumi_auth_sessions from anon, authenticated;
revoke all on table public.rumi_password_history from anon, authenticated;
revoke all on table public.rumi_login_throttles from anon, authenticated;
revoke all on table public.rumi_attendance_events from anon, authenticated;
revoke all on table public.rumi_attendance_correction_requests from anon, authenticated;

revoke execute on function public.rumi_auth_register_failure(text,bigint,timestamptz) from public, anon, authenticated;
revoke execute on function public.rumi_auth_clear_failures(text,bigint,timestamptz) from public, anon, authenticated;
revoke execute on function public.rumi_clock_shift_v55(bigint,bigint,text,double precision,double precision,double precision,text,timestamptz,text,timestamptz) from public, anon, authenticated;
revoke execute on function public.rumi_review_overtime_v55(bigint,integer,bigint,text) from public, anon, authenticated;

grant execute on function public.rumi_auth_register_failure(text,bigint,timestamptz) to service_role;
grant execute on function public.rumi_auth_clear_failures(text,bigint,timestamptz) to service_role;
grant execute on function public.rumi_clock_shift_v55(bigint,bigint,text,double precision,double precision,double precision,text,timestamptz,text,timestamptz) to service_role;
grant execute on function public.rumi_review_overtime_v55(bigint,integer,bigint,text) to service_role;

commit;
