-- RUMI Manager 6.2 - Attendance alerts & payroll PDF metadata
-- Chỉ tạo/sửa các đối tượng có tiền tố rumi_. Không đụng dữ liệu IC3 Smart Class.

begin;

alter table public.rumi_settings
  add column if not exists attendance_warning_minutes integer not null default 15,
  add column if not exists attendance_no_show_minutes integer not null default 30,
  add column if not exists attendance_absent_after_end_minutes integer not null default 0,
  add column if not exists attendance_alert_refresh_seconds integer not null default 60;

alter table public.rumi_settings drop constraint if exists rumi_settings_attendance_alert_check;
alter table public.rumi_settings add constraint rumi_settings_attendance_alert_check check (
  attendance_warning_minutes between 5 and 180 and
  attendance_no_show_minutes between attendance_warning_minutes and 360 and
  attendance_absent_after_end_minutes between 0 and 240 and
  attendance_alert_refresh_seconds between 30 and 600
);

create table if not exists public.rumi_shift_attendance_alerts (
  id bigint generated by default as identity primary key,
  shift_id bigint not null unique references public.rumi_shifts(id) on delete cascade,
  employee_id bigint not null references public.rumi_employees(id) on delete cascade,
  status text not null,
  severity text not null default 'warning',
  minutes_late integer not null default 0,
  first_detected_at timestamptz not null default now(),
  last_detected_at timestamptz not null default now(),
  notified_employee_at timestamptz,
  notified_admin_at timestamptz,
  resolved_at timestamptz,
  resolution_note text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint rumi_shift_attendance_alert_status_check check (
    status in (
      'Đến giờ chấm công',
      'Đi trễ chưa chấm',
      'Nguy cơ vắng ca',
      'Vắng ca',
      'Đến giờ chấm ra',
      'Thiếu giờ ra',
      'Đã xử lý'
    )
  ),
  constraint rumi_shift_attendance_alert_severity_check check (
    severity in ('info','warning','danger')
  )
);

create index if not exists rumi_shift_attendance_alerts_employee_idx
  on public.rumi_shift_attendance_alerts(employee_id, resolved_at, last_detected_at desc);
create index if not exists rumi_shift_attendance_alerts_status_idx
  on public.rumi_shift_attendance_alerts(status, resolved_at, last_detected_at desc);

-- Dùng trigger cập nhật updated_at nếu hàm từ migration v4 đã tồn tại.
drop trigger if exists rumi_shift_attendance_alerts_touch_updated_at on public.rumi_shift_attendance_alerts;
create trigger rumi_shift_attendance_alerts_touch_updated_at
before update on public.rumi_shift_attendance_alerts
for each row execute function public.rumi_touch_updated_at();

alter table public.rumi_payroll_items
  add column if not exists late_unclocked_count integer not null default 0,
  add column if not exists no_show_risk_count integer not null default 0,
  add column if not exists absent_shift_count integer not null default 0;



-- --------------------------------------------------------------------------
-- Chấm công v6.2: cho phép nhân viên chấm vào muộn trong khi ca vẫn đang diễn ra.
-- Lượt chấm sau ngưỡng cảnh báo/nguy cơ vắng được ghi nhận rủi ro để admin kiểm tra.
-- Sau khi ca kết thúc, nhân viên phải gửi yêu cầu sửa chấm công.
-- --------------------------------------------------------------------------
create or replace function public.rumi_clock_shift_v62(
  p_shift_id bigint,
  p_employee_id bigint,
  p_action text,
  p_lat double precision,
  p_lng double precision,
  p_accuracy double precision,
  p_device_hash text,
  p_client_time timestamptz,
  p_ip_hash text default '',
  p_now timestamptz default now()
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_shift public.rumi_shifts%rowtype;
  v_location public.rumi_locations%rowtype;
  v_settings public.rumi_settings%rowtype;
  v_att public.rumi_attendance%rowtype;
  v_shift_start timestamptz;
  v_shift_end timestamptz;
  v_distance double precision;
  v_action text;
  v_scheduled integer;
  v_worked integer;
  v_base integer;
  v_payable integer;
  v_late integer;
  v_early integer;
  v_ot integer;
  v_ot_approved integer;
  v_status text;
  v_risk text := 'Thấp';
  v_risks jsonb := '[]'::jsonb;
  v_shared_device boolean := false;
begin
  if p_lat is null or p_lng is null then raise exception 'Không nhận được vị trí GPS'; end if;
  if p_client_time is null then raise exception 'Vị trí GPS không có thời gian đo'; end if;

  select * into v_settings from public.rumi_settings where id = 1;
  if not found then raise exception 'Chưa cấu hình quy định chấm công'; end if;

  if abs(extract(epoch from (p_now - p_client_time))) > v_settings.location_freshness_seconds then
    raise exception 'Vị trí GPS đã cũ. Hãy bật vị trí chính xác và thử lại';
  end if;
  if p_accuracy is null or p_accuracy <= 0 or p_accuracy > v_settings.max_gps_accuracy_m then
    raise exception 'GPS chưa đủ chính xác. Sai số hiện tại % m, tối đa % m', round(coalesce(p_accuracy,9999)::numeric,0), v_settings.max_gps_accuracy_m;
  end if;

  select * into v_shift from public.rumi_shifts where id = p_shift_id for update;
  if not found then raise exception 'Không tìm thấy ca làm'; end if;
  if v_shift.employee_id <> p_employee_id then raise exception 'Ca làm không thuộc tài khoản này'; end if;
  if v_shift.status not in ('Đã xếp','Đã xác nhận') then raise exception 'Ca làm chưa được chốt để chấm công'; end if;
  if v_shift.location_id is null then raise exception 'Ca làm chưa được cấu hình vị trí cửa hàng'; end if;

  select * into v_location from public.rumi_locations where id = v_shift.location_id and active = true;
  if not found then raise exception 'Vị trí cửa hàng không tồn tại hoặc đã tắt'; end if;

  v_distance := 6371000 * 2 * asin(sqrt(
    power(sin(radians(p_lat - v_location.latitude) / 2), 2) +
    cos(radians(v_location.latitude)) * cos(radians(p_lat)) *
    power(sin(radians(p_lng - v_location.longitude) / 2), 2)
  ));
  if v_distance > v_location.radius_m then
    raise exception 'Bạn đang cách cửa hàng % m, phạm vi cho phép % m', round(v_distance::numeric,0), v_location.radius_m;
  end if;

  if p_accuracy > v_settings.max_gps_accuracy_m * 0.75 then
    v_risk := 'Trung bình';
    v_risks := v_risks || jsonb_build_array('Sai số GPS gần mức tối đa');
  end if;

  if coalesce(p_device_hash,'') <> '' then
    select exists(
      select 1 from public.rumi_attendance_events e
      where e.device_id_hash = p_device_hash
        and e.employee_id is distinct from p_employee_id
        and e.success = true
        and e.created_at > p_now - interval '30 minutes'
    ) into v_shared_device;
    if v_shared_device then
      v_risk := 'Cao';
      v_risks := v_risks || jsonb_build_array('Thiết bị vừa chấm công cho tài khoản khác');
    end if;
  end if;

  v_shift_start := (v_shift.shift_date + v_shift.start_time) at time zone v_settings.timezone;
  v_shift_end := (v_shift.shift_date + v_shift.end_time) at time zone v_settings.timezone;
  v_scheduled := greatest(0, floor(extract(epoch from (v_shift_end - v_shift_start)) / 60)::integer);

  select * into v_att from public.rumi_attendance where shift_id = p_shift_id for update;
  v_action := lower(coalesce(p_action,'auto'));
  if v_action = 'auto' then
    v_action := case when found and v_att.check_out_at is null then 'checkout' else 'checkin' end;
  end if;

  if v_action = 'checkin' then
    if found then raise exception 'Ca này đã chấm công vào'; end if;
    if p_now < v_shift_start - make_interval(mins => v_settings.checkin_before_minutes) then
      raise exception 'Chỉ được chấm công vào sớm nhất lúc %',
        to_char(v_shift_start - make_interval(mins => v_settings.checkin_before_minutes),'HH24:MI');
    end if;
    if p_now >= v_shift_end + make_interval(mins => coalesce(v_settings.attendance_absent_after_end_minutes,0)) then
      raise exception 'Ca đã kết thúc. Hãy gửi yêu cầu sửa chấm công cho quản lý';
    end if;

    v_late := greatest(0, floor(extract(epoch from (p_now - v_shift_start)) / 60)::integer);
    if v_late > coalesce(v_settings.attendance_no_show_minutes,30) then
      v_risk := 'Cao';
      v_risks := v_risks || jsonb_build_array('Chấm vào sau ngưỡng nguy cơ vắng ca');
    elsif v_late > v_settings.checkin_after_minutes then
      if v_risk <> 'Cao' then v_risk := 'Trung bình'; end if;
      v_risks := v_risks || jsonb_build_array('Chấm vào muộn ngoài cửa sổ thông thường');
    end if;
    insert into public.rumi_attendance(
      shift_id, employee_id, work_date, check_in, check_in_at,
      check_in_lat, check_in_lng, check_in_accuracy_m, check_in_distance_m,
      scheduled_minutes, scheduled_hours, late_minutes,
      status, note, device_id_hash, client_position_at, risk_level, risk_reasons,
      review_status
    ) values (
      p_shift_id, p_employee_id, v_shift.shift_date, (p_now at time zone v_settings.timezone)::time,
      p_now, p_lat, p_lng, p_accuracy, v_distance,
      v_scheduled, round(v_scheduled::numeric / 60, 2), v_late,
      case when v_late > v_settings.late_grace_minutes then 'Đi trễ' else 'Đang làm' end,
      '', coalesce(p_device_hash,''), p_client_time, v_risk, v_risks,
      case when v_risk = 'Cao' then 'Chờ duyệt' else 'Không cần duyệt' end
    ) returning * into v_att;

    insert into public.rumi_attendance_events(
      shift_id, employee_id, action, success, reason, latitude, longitude,
      accuracy_m, distance_m, device_id_hash, ip_hash, client_position_at
    ) values (
      p_shift_id, p_employee_id, 'checkin', true, case when v_late > v_settings.checkin_after_minutes then 'Chấm vào muộn' else '' end, p_lat, p_lng,
      p_accuracy, v_distance, coalesce(p_device_hash,''), coalesce(p_ip_hash,''), p_client_time
    );

    return jsonb_build_object(
      'attendance_id', v_att.id, 'action','checkin',
      'time',to_char(p_now at time zone v_settings.timezone,'HH24:MI'),
      'distance_m',round(v_distance::numeric,1), 'accuracy_m',round(p_accuracy::numeric,0),
      'late_minutes',v_late, 'attendance_state',case when v_late > coalesce(v_settings.attendance_no_show_minutes,30) then 'Đã chấm vào muộn - cần duyệt' when v_late > v_settings.checkin_after_minutes then 'Đã chấm vào muộn' else 'Đã chấm vào' end, 'risk_level',v_risk, 'review_status',v_att.review_status
    );
  end if;

  if v_action = 'checkout' then
    if not found then raise exception 'Bạn chưa chấm công vào ca này'; end if;
    if v_att.check_out_at is not null then raise exception 'Ca này đã chấm công ra'; end if;
    if p_now < v_shift_end - make_interval(mins => v_settings.checkout_before_minutes)
       or p_now > v_shift_end + make_interval(mins => v_settings.checkout_after_minutes) then
      raise exception 'Chỉ được chấm công ra từ % đến %',
        to_char(v_shift_end - make_interval(mins => v_settings.checkout_before_minutes),'HH24:MI'),
        to_char(v_shift_end + make_interval(mins => v_settings.checkout_after_minutes),'HH24:MI');
    end if;
    if p_now < v_att.check_in_at + make_interval(mins => v_settings.min_clock_gap_minutes) then
      raise exception 'Thời gian vào và ra ca quá gần nhau';
    end if;

    v_worked := greatest(0, floor(extract(epoch from (p_now - v_att.check_in_at)) / 60)::integer);
    v_late := greatest(0, floor(extract(epoch from (v_att.check_in_at - v_shift_start)) / 60)::integer);
    v_early := greatest(0, floor(extract(epoch from (v_shift_end - p_now)) / 60)::integer);
    v_ot := least(v_settings.max_overtime_minutes,
      greatest(0, floor(extract(epoch from (p_now - v_shift_end)) / 60)::integer));

    -- Chỉ trả lương trong khung ca. Vào sớm không làm tăng lương.
    v_base := greatest(0, floor(extract(epoch from (
      least(p_now, v_shift_end) - greatest(v_att.check_in_at, v_shift_start)
    )) / 60)::integer - coalesce(v_att.break_minutes,0));
    v_ot_approved := case when v_settings.overtime_requires_approval then 0 else v_ot end;
    v_payable := greatest(0, v_base + v_ot_approved);

    if v_ot > 0 and v_settings.overtime_requires_approval then
      v_status := 'Chờ duyệt tăng ca';
    elsif v_late > v_settings.late_grace_minutes and v_early > v_settings.early_leave_grace_minutes then
      v_status := 'Đi trễ & về sớm';
    elsif v_late > v_settings.late_grace_minutes then
      v_status := 'Đi trễ';
    elsif v_early > v_settings.early_leave_grace_minutes then
      v_status := 'Về sớm';
    elsif v_ot > 0 then
      v_status := 'Có tăng ca';
    else
      v_status := 'Hoàn thành';
    end if;

    update public.rumi_attendance set
      check_out = (p_now at time zone v_settings.timezone)::time,
      check_out_at = p_now,
      check_out_lat = p_lat,
      check_out_lng = p_lng,
      check_out_accuracy_m = p_accuracy,
      check_out_distance_m = v_distance,
      worked_minutes = v_worked,
      base_payable_minutes = v_base,
      payable_minutes = v_payable,
      overtime_requested_minutes = v_ot,
      overtime_approved_minutes = v_ot_approved,
      overtime_minutes = v_ot,
      overtime_status = case when v_ot = 0 then 'Không có' when v_settings.overtime_requires_approval then 'Chờ duyệt' else 'Đã duyệt' end,
      early_leave_minutes = v_early,
      late_minutes = v_late,
      hours = round(v_payable::numeric / 60, 2),
      payable_hours = round(v_payable::numeric / 60, 2),
      status = v_status,
      calculation_note = concat_ws(' · ',
        case when v_late > 0 then 'Trễ ' || v_late || ' phút' end,
        case when v_early > 0 then 'Về sớm ' || v_early || ' phút' end,
        case when v_ot > 0 then 'Tăng ca ' || v_ot || ' phút' end,
        'Tính lương ' || v_payable || ' phút'
      ),
      risk_level = case when v_risk = 'Cao' or risk_level = 'Cao' then 'Cao' when v_risk = 'Trung bình' or risk_level = 'Trung bình' then 'Trung bình' else 'Thấp' end,
      risk_reasons = risk_reasons || v_risks,
      review_status = case when v_risk = 'Cao' then 'Chờ duyệt' else review_status end,
      client_position_at = p_client_time
    where id = v_att.id
    returning * into v_att;

    insert into public.rumi_attendance_events(
      shift_id, employee_id, action, success, reason, latitude, longitude,
      accuracy_m, distance_m, device_id_hash, ip_hash, client_position_at
    ) values (
      p_shift_id, p_employee_id, 'checkout', true, '', p_lat, p_lng,
      p_accuracy, v_distance, coalesce(p_device_hash,''), coalesce(p_ip_hash,''), p_client_time
    );

    return jsonb_build_object(
      'attendance_id', v_att.id, 'action','checkout',
      'time',to_char(p_now at time zone v_settings.timezone,'HH24:MI'),
      'distance_m',round(v_distance::numeric,1), 'accuracy_m',round(p_accuracy::numeric,0),
      'worked_minutes',v_worked, 'base_payable_minutes',v_base,
      'overtime_requested_minutes',v_ot, 'overtime_approved_minutes',v_ot_approved,
      'payable_minutes',v_payable, 'hours',round(v_payable::numeric / 60, 2),
      'overtime_status',v_att.overtime_status, 'risk_level',v_att.risk_level,
      'review_status',v_att.review_status
    );
  end if;

  raise exception 'Hành động chấm công không hợp lệ';
end;
$$;

revoke execute on function public.rumi_clock_shift_v62(bigint,bigint,text,double precision,double precision,double precision,text,timestamptz,text,timestamptz) from public, anon, authenticated;
grant execute on function public.rumi_clock_shift_v62(bigint,bigint,text,double precision,double precision,double precision,text,timestamptz,text,timestamptz) to service_role;

alter table public.rumi_shift_attendance_alerts enable row level security;
revoke all on table public.rumi_shift_attendance_alerts from anon, authenticated;

commit;
