-- ============================================================================
-- RUMI Manager v4.0 — Authentication, role permissions, scheduling and GPS
-- Idempotent migration for the SAME Supabase project as IC3 Smart Class.
-- This script only creates/alters objects prefixed with rumi_.
-- It does not read, update or delete any IC3 table.
-- ============================================================================

begin;

-- --------------------------------------------------------------------------
-- Existing core tables (created when installing fresh; preserved on upgrade)
-- --------------------------------------------------------------------------
create table if not exists public.rumi_employees (
  id bigint generated by default as identity primary key,
  code text not null unique,
  name text not null,
  phone text not null default '',
  email text not null default '',
  role text not null default 'Nhân viên',
  hourly_wage numeric(14,2) not null default 25000 check (hourly_wage >= 0),
  status text not null default 'Đang làm',
  joined_at date not null default current_date,
  created_at timestamptz not null default now()
);

alter table public.rumi_employees add column if not exists email text not null default '';

create table if not exists public.rumi_shifts (
  id bigint generated by default as identity primary key,
  employee_id bigint not null references public.rumi_employees(id) on delete cascade,
  shift_date date not null,
  start_time time without time zone not null,
  end_time time without time zone not null,
  note text not null default '',
  status text not null default 'Đã xếp',
  created_at timestamptz not null default now(),
  constraint rumi_shifts_time_check check (end_time > start_time)
);

create table if not exists public.rumi_attendance (
  id bigint generated by default as identity primary key,
  employee_id bigint not null references public.rumi_employees(id) on delete cascade,
  work_date date not null,
  check_in time without time zone not null,
  check_out time without time zone,
  hours numeric(8,2) not null default 0 check (hours >= 0),
  status text not null default 'Đang làm',
  note text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.rumi_inventory (
  id bigint generated by default as identity primary key,
  name text not null unique,
  category text not null default 'Nguyên liệu',
  quantity numeric(14,3) not null default 0 check (quantity >= 0),
  unit text not null default 'kg',
  min_stock numeric(14,3) not null default 0 check (min_stock >= 0),
  cost numeric(14,2) not null default 0 check (cost >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.rumi_withdrawals (
  id bigint generated by default as identity primary key,
  inventory_id bigint not null references public.rumi_inventory(id) on delete restrict,
  employee_id bigint references public.rumi_employees(id) on delete set null,
  quantity numeric(14,3) not null check (quantity > 0),
  taken_at date not null default current_date,
  note text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.rumi_purchase_requests (
  id bigint generated by default as identity primary key,
  item_name text not null,
  quantity numeric(14,3) not null check (quantity > 0),
  unit text not null,
  reason text not null default '',
  requester_name text not null,
  requested_at date not null default current_date,
  priority text not null default 'Bình thường',
  status text not null default 'Chờ mua',
  created_at timestamptz not null default now()
);

create table if not exists public.rumi_payroll_adjustments (
  id bigint generated by default as identity primary key,
  employee_id bigint not null references public.rumi_employees(id) on delete cascade,
  month text not null check (month ~ '^\d{4}-\d{2}$'),
  bonus numeric(14,2) not null default 0 check (bonus >= 0),
  penalty numeric(14,2) not null default 0 check (penalty >= 0),
  advance_pay numeric(14,2) not null default 0 check (advance_pay >= 0),
  note text not null default '',
  created_at timestamptz not null default now(),
  unique (employee_id, month)
);

create table if not exists public.rumi_payroll_payments (
  id bigint generated by default as identity primary key,
  employee_id bigint not null references public.rumi_employees(id) on delete cascade,
  month text not null check (month ~ '^\d{4}-\d{2}$'),
  status text not null default 'Chưa thanh toán',
  paid_at timestamptz,
  created_at timestamptz not null default now(),
  unique (employee_id, month)
);

-- --------------------------------------------------------------------------
-- Authentication and role isolation
-- --------------------------------------------------------------------------
create table if not exists public.rumi_users (
  id bigint generated by default as identity primary key,
  username text not null unique,
  password_hash text not null,
  password_salt text not null,
  role text not null check (role in ('admin', 'employee')),
  employee_id bigint unique references public.rumi_employees(id) on delete cascade,
  active boolean not null default true,
  last_login_at timestamptz,
  created_at timestamptz not null default now(),
  constraint rumi_users_employee_role_check check (
    (role = 'admin') or (role = 'employee' and employee_id is not null)
  )
);

create table if not exists public.rumi_locations (
  id bigint generated by default as identity primary key,
  name text not null,
  address text not null default '',
  latitude double precision not null check (latitude between -90 and 90),
  longitude double precision not null check (longitude between -180 and 180),
  radius_m integer not null default 100 check (radius_m between 20 and 2000),
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.rumi_settings (
  id smallint primary key default 1 check (id = 1),
  timezone text not null default 'Asia/Ho_Chi_Minh',
  checkin_before_minutes integer not null default 15 check (checkin_before_minutes between 0 and 180),
  checkin_after_minutes integer not null default 5 check (checkin_after_minutes between 0 and 180),
  checkout_before_minutes integer not null default 5 check (checkout_before_minutes between 0 and 180),
  checkout_after_minutes integer not null default 5 check (checkout_after_minutes between 0 and 360),
  max_gps_accuracy_m integer not null default 150 check (max_gps_accuracy_m between 10 and 1000),
  updated_at timestamptz not null default now()
);
insert into public.rumi_settings(id) values (1) on conflict (id) do nothing;

create table if not exists public.rumi_availability_requests (
  id bigint generated by default as identity primary key,
  employee_id bigint not null references public.rumi_employees(id) on delete cascade,
  work_date date not null,
  start_time time without time zone not null,
  end_time time without time zone not null,
  note text not null default '',
  status text not null default 'Chờ duyệt' check (status in ('Chờ duyệt','Đã duyệt','Từ chối','Đã xếp ca')),
  admin_note text not null default '',
  reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  constraint rumi_availability_time_check check (end_time > start_time)
);

create table if not exists public.rumi_leave_requests (
  id bigint generated by default as identity primary key,
  employee_id bigint not null references public.rumi_employees(id) on delete cascade,
  start_date date not null,
  end_date date not null,
  reason text not null,
  status text not null default 'Chờ duyệt' check (status in ('Chờ duyệt','Đã duyệt','Từ chối')),
  admin_note text not null default '',
  reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  constraint rumi_leave_date_check check (end_date >= start_date)
);

create table if not exists public.rumi_shift_change_requests (
  id bigint generated by default as identity primary key,
  shift_id bigint not null references public.rumi_shifts(id) on delete cascade,
  requester_id bigint not null references public.rumi_employees(id) on delete cascade,
  request_type text not null default 'Tìm người thay' check (request_type in ('Tìm người thay','Đổi ca','Xin nghỉ ca')),
  reason text not null,
  status text not null default 'Chờ xử lý' check (status in ('Chờ xử lý','Đã duyệt','Từ chối','Đã hủy')),
  replacement_employee_id bigint references public.rumi_employees(id) on delete set null,
  admin_note text not null default '',
  reviewed_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.rumi_notifications (
  id bigint generated by default as identity primary key,
  employee_id bigint references public.rumi_employees(id) on delete cascade,
  audience_role text check (audience_role in ('admin','employee')),
  title text not null,
  message text not null,
  type text not null default 'info',
  link text not null default '',
  read_at timestamptz,
  created_at timestamptz not null default now(),
  constraint rumi_notification_target_check check (employee_id is not null or audience_role is not null)
);

create table if not exists public.rumi_audit_logs (
  id bigint generated by default as identity primary key,
  user_id bigint references public.rumi_users(id) on delete set null,
  action text not null,
  entity_type text not null,
  entity_id text not null default '',
  detail jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

-- --------------------------------------------------------------------------
-- Upgrade existing tables
-- --------------------------------------------------------------------------
alter table public.rumi_shifts add column if not exists location_id bigint references public.rumi_locations(id) on delete restrict;
alter table public.rumi_shifts add column if not exists created_by bigint references public.rumi_users(id) on delete set null;
alter table public.rumi_shifts add column if not exists availability_request_id bigint references public.rumi_availability_requests(id) on delete set null;

alter table public.rumi_attendance add column if not exists shift_id bigint references public.rumi_shifts(id) on delete cascade;
alter table public.rumi_attendance add column if not exists check_in_at timestamptz;
alter table public.rumi_attendance add column if not exists check_out_at timestamptz;
alter table public.rumi_attendance add column if not exists check_in_lat double precision;
alter table public.rumi_attendance add column if not exists check_in_lng double precision;
alter table public.rumi_attendance add column if not exists check_in_accuracy_m double precision;
alter table public.rumi_attendance add column if not exists check_in_distance_m double precision;
alter table public.rumi_attendance add column if not exists check_out_lat double precision;
alter table public.rumi_attendance add column if not exists check_out_lng double precision;
alter table public.rumi_attendance add column if not exists check_out_accuracy_m double precision;
alter table public.rumi_attendance add column if not exists check_out_distance_m double precision;

alter table public.rumi_purchase_requests add column if not exists requester_employee_id bigint references public.rumi_employees(id) on delete set null;

-- Old v3 allowed only one attendance row per employee/day. v4 supports multiple shifts.
alter table public.rumi_attendance drop constraint if exists rumi_attendance_employee_id_work_date_key;
create unique index if not exists rumi_attendance_shift_unique
  on public.rumi_attendance(shift_id);

-- --------------------------------------------------------------------------
-- Indexes
-- --------------------------------------------------------------------------
create index if not exists rumi_shifts_date_idx on public.rumi_shifts (shift_date, start_time);
create index if not exists rumi_shifts_employee_date_idx on public.rumi_shifts (employee_id, shift_date);
create index if not exists rumi_shifts_location_date_idx on public.rumi_shifts (location_id, shift_date);
create index if not exists rumi_attendance_date_idx on public.rumi_attendance (work_date, employee_id);
create index if not exists rumi_availability_date_idx on public.rumi_availability_requests (work_date, status, start_time);
create index if not exists rumi_leave_date_idx on public.rumi_leave_requests (start_date, end_date, status);
create index if not exists rumi_shift_change_status_idx on public.rumi_shift_change_requests (status, created_at desc);
create index if not exists rumi_notifications_employee_idx on public.rumi_notifications (employee_id, read_at, created_at desc);
create index if not exists rumi_notifications_role_idx on public.rumi_notifications (audience_role, read_at, created_at desc);
create index if not exists rumi_withdrawals_date_idx on public.rumi_withdrawals (taken_at desc, id desc);
create index if not exists rumi_purchase_status_idx on public.rumi_purchase_requests (status, priority, requested_at desc);

-- --------------------------------------------------------------------------
-- Utility trigger
-- --------------------------------------------------------------------------
create or replace function public.rumi_touch_updated_at()
returns trigger language plpgsql set search_path = public as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists rumi_inventory_touch_updated_at on public.rumi_inventory;
create trigger rumi_inventory_touch_updated_at
before update on public.rumi_inventory
for each row execute function public.rumi_touch_updated_at();

drop trigger if exists rumi_settings_touch_updated_at on public.rumi_settings;
create trigger rumi_settings_touch_updated_at
before update on public.rumi_settings
for each row execute function public.rumi_touch_updated_at();

-- --------------------------------------------------------------------------
-- Inventory transactions
-- --------------------------------------------------------------------------
create or replace function public.rumi_restock_inventory(p_inventory_id bigint, p_quantity numeric)
returns jsonb language plpgsql security definer set search_path = public as $$
declare v_remaining numeric;
begin
  if p_quantity is null or p_quantity <= 0 then raise exception 'Số lượng nhập kho phải lớn hơn 0'; end if;
  update public.rumi_inventory set quantity = quantity + p_quantity
  where id = p_inventory_id returning quantity into v_remaining;
  if not found then raise exception 'Không tìm thấy nguyên liệu'; end if;
  return jsonb_build_object('remaining', v_remaining);
end;
$$;

create or replace function public.rumi_withdraw_inventory(
  p_inventory_id bigint, p_employee_id bigint, p_quantity numeric,
  p_taken_at date, p_note text default ''
)
returns jsonb language plpgsql security definer set search_path = public as $$
declare
  v_item public.rumi_inventory%rowtype;
  v_remaining numeric;
  v_suggested numeric;
  v_requester text := 'Hệ thống';
  v_purchase_created boolean := false;
begin
  if p_quantity is null or p_quantity <= 0 then raise exception 'Số lượng lấy phải lớn hơn 0'; end if;
  select * into v_item from public.rumi_inventory where id = p_inventory_id for update;
  if not found then raise exception 'Không tìm thấy nguyên liệu'; end if;
  if p_quantity > v_item.quantity then raise exception 'Kho chỉ còn % %', v_item.quantity, v_item.unit; end if;
  if p_employee_id is not null then
    select name into v_requester from public.rumi_employees where id = p_employee_id;
    if not found then raise exception 'Không tìm thấy nhân viên'; end if;
  end if;
  v_remaining := v_item.quantity - p_quantity;
  update public.rumi_inventory set quantity = v_remaining where id = p_inventory_id;
  insert into public.rumi_withdrawals(inventory_id, employee_id, quantity, taken_at, note)
  values (p_inventory_id, p_employee_id, p_quantity, coalesce(p_taken_at,current_date), coalesce(p_note,''));
  if v_remaining <= v_item.min_stock and not exists (
    select 1 from public.rumi_purchase_requests where item_name = v_item.name and status = 'Chờ mua'
  ) then
    v_suggested := greatest(v_item.min_stock * 2 - v_remaining, v_item.min_stock);
    insert into public.rumi_purchase_requests(
      item_name, quantity, unit, reason, requester_name, requester_employee_id,
      requested_at, priority, status
    ) values (
      v_item.name, v_suggested, v_item.unit, 'Tồn kho xuống dưới mức tối thiểu',
      v_requester, p_employee_id, current_date, 'Gấp', 'Chờ mua'
    );
    v_purchase_created := true;
  end if;
  return jsonb_build_object('remaining',v_remaining,'unit',v_item.unit,'purchase_request_created',v_purchase_created);
end;
$$;

-- --------------------------------------------------------------------------
-- GPS attendance. All time checks happen in PostgreSQL in one transaction.
-- Default windows: check-in -15/+5 minutes; check-out -5/+5 minutes.
-- --------------------------------------------------------------------------
create or replace function public.rumi_clock_shift(
  p_shift_id bigint,
  p_employee_id bigint,
  p_action text,
  p_lat double precision,
  p_lng double precision,
  p_accuracy double precision,
  p_now timestamptz default now()
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_shift public.rumi_shifts%rowtype;
  v_location public.rumi_locations%rowtype;
  v_settings public.rumi_settings%rowtype;
  v_attendance public.rumi_attendance%rowtype;
  v_shift_start timestamptz;
  v_shift_end timestamptz;
  v_distance double precision;
  v_action text;
  v_hours numeric(8,2);
begin
  if p_lat is null or p_lng is null then raise exception 'Không nhận được vị trí GPS'; end if;
  select * into v_settings from public.rumi_settings where id = 1;
  select * into v_shift from public.rumi_shifts where id = p_shift_id for update;
  if not found then raise exception 'Không tìm thấy ca làm'; end if;
  if v_shift.employee_id <> p_employee_id then raise exception 'Ca làm không thuộc tài khoản này'; end if;
  if v_shift.status not in ('Đã xếp','Đã xác nhận') then raise exception 'Ca làm không ở trạng thái có thể chấm công'; end if;
  if v_shift.location_id is null then raise exception 'Ca làm chưa được cấu hình vị trí cửa hàng'; end if;
  select * into v_location from public.rumi_locations where id = v_shift.location_id and active = true;
  if not found then raise exception 'Vị trí cửa hàng không tồn tại hoặc đã tắt'; end if;

  if p_accuracy is null or p_accuracy > v_settings.max_gps_accuracy_m then
    raise exception 'GPS chưa đủ chính xác. Sai số hiện tại % m, tối đa % m', round(coalesce(p_accuracy,9999)::numeric,0), v_settings.max_gps_accuracy_m;
  end if;

  v_distance := 6371000 * 2 * asin(sqrt(
    power(sin(radians(p_lat - v_location.latitude) / 2), 2) +
    cos(radians(v_location.latitude)) * cos(radians(p_lat)) *
    power(sin(radians(p_lng - v_location.longitude) / 2), 2)
  ));
  if v_distance > v_location.radius_m then
    raise exception 'Bạn đang cách cửa hàng % m, phạm vi cho phép % m', round(v_distance::numeric,0), v_location.radius_m;
  end if;

  v_shift_start := (v_shift.shift_date + v_shift.start_time) at time zone v_settings.timezone;
  v_shift_end := (v_shift.shift_date + v_shift.end_time) at time zone v_settings.timezone;

  select * into v_attendance from public.rumi_attendance where shift_id = p_shift_id for update;
  v_action := lower(coalesce(p_action,'auto'));
  if v_action = 'auto' then
    v_action := case when found and v_attendance.check_out_at is null then 'checkout' else 'checkin' end;
  end if;

  if v_action = 'checkin' then
    if found then raise exception 'Ca này đã chấm công vào'; end if;
    if p_now < v_shift_start - make_interval(mins => v_settings.checkin_before_minutes)
       or p_now > v_shift_start + make_interval(mins => v_settings.checkin_after_minutes) then
      raise exception 'Chỉ được chấm công vào từ % đến %',
        to_char(v_shift_start - make_interval(mins => v_settings.checkin_before_minutes),'HH24:MI'),
        to_char(v_shift_start + make_interval(mins => v_settings.checkin_after_minutes),'HH24:MI');
    end if;
    insert into public.rumi_attendance(
      shift_id, employee_id, work_date, check_in, check_in_at,
      check_in_lat, check_in_lng, check_in_accuracy_m, check_in_distance_m,
      status, note
    ) values (
      p_shift_id, p_employee_id, v_shift.shift_date, (p_now at time zone v_settings.timezone)::time,
      p_now, p_lat, p_lng, p_accuracy, v_distance, 'Đang làm', ''
    ) returning * into v_attendance;
    return jsonb_build_object('action','checkin','time',to_char(p_now at time zone v_settings.timezone,'HH24:MI'),'distance_m',round(v_distance::numeric,1));
  end if;

  if v_action = 'checkout' then
    if not found then raise exception 'Bạn chưa chấm công vào ca này'; end if;
    if v_attendance.check_out_at is not null then raise exception 'Ca này đã chấm công ra'; end if;
    if p_now < v_shift_end - make_interval(mins => v_settings.checkout_before_minutes)
       or p_now > v_shift_end + make_interval(mins => v_settings.checkout_after_minutes) then
      raise exception 'Chỉ được chấm công ra từ % đến %',
        to_char(v_shift_end - make_interval(mins => v_settings.checkout_before_minutes),'HH24:MI'),
        to_char(v_shift_end + make_interval(mins => v_settings.checkout_after_minutes),'HH24:MI');
    end if;
    v_hours := round((extract(epoch from (p_now - v_attendance.check_in_at)) / 3600)::numeric, 2);
    update public.rumi_attendance set
      check_out = (p_now at time zone v_settings.timezone)::time,
      check_out_at = p_now,
      check_out_lat = p_lat,
      check_out_lng = p_lng,
      check_out_accuracy_m = p_accuracy,
      check_out_distance_m = v_distance,
      hours = greatest(v_hours,0),
      status = 'Hoàn thành'
    where id = v_attendance.id;
    return jsonb_build_object('action','checkout','time',to_char(p_now at time zone v_settings.timezone,'HH24:MI'),'hours',greatest(v_hours,0),'distance_m',round(v_distance::numeric,1));
  end if;

  raise exception 'Hành động chấm công không hợp lệ';
end;
$$;

-- --------------------------------------------------------------------------
-- Assign a free employee to a replacement request atomically.
-- --------------------------------------------------------------------------
create or replace function public.rumi_assign_replacement(
  p_request_id bigint,
  p_replacement_employee_id bigint,
  p_admin_note text default ''
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_request public.rumi_shift_change_requests%rowtype;
  v_shift public.rumi_shifts%rowtype;
  v_old_employee bigint;
begin
  select * into v_request from public.rumi_shift_change_requests where id = p_request_id for update;
  if not found then raise exception 'Không tìm thấy yêu cầu thay ca'; end if;
  if v_request.status <> 'Chờ xử lý' then raise exception 'Yêu cầu này đã được xử lý'; end if;
  select * into v_shift from public.rumi_shifts where id = v_request.shift_id for update;
  if not found then raise exception 'Không tìm thấy ca làm'; end if;
  if p_replacement_employee_id = v_shift.employee_id then raise exception 'Hãy chọn một nhân viên khác'; end if;
  if not exists (select 1 from public.rumi_employees where id=p_replacement_employee_id and status='Đang làm') then
    raise exception 'Nhân viên thay ca không còn hoạt động';
  end if;
  if exists (
    select 1 from public.rumi_shifts s
    where s.employee_id=p_replacement_employee_id and s.shift_date=v_shift.shift_date
      and s.status in ('Đã xếp','Đã xác nhận') and s.id<>v_shift.id
      and s.start_time < v_shift.end_time and s.end_time > v_shift.start_time
  ) then raise exception 'Nhân viên được chọn đang trùng ca'; end if;
  if exists (
    select 1 from public.rumi_leave_requests l
    where l.employee_id=p_replacement_employee_id and l.status='Đã duyệt'
      and v_shift.shift_date between l.start_date and l.end_date
  ) then raise exception 'Nhân viên được chọn đang nghỉ phép'; end if;
  if not exists (
    select 1 from public.rumi_availability_requests a
    where a.employee_id=p_replacement_employee_id and a.work_date=v_shift.shift_date
      and a.status in ('Đã duyệt','Đã xếp ca')
      and a.start_time <= v_shift.start_time and a.end_time >= v_shift.end_time
  ) then raise exception 'Nhân viên chưa đăng ký rảnh trong khung giờ này'; end if;

  v_old_employee := v_shift.employee_id;
  update public.rumi_shifts set employee_id=p_replacement_employee_id, note=concat_ws(' · ',nullif(note,''),'Thay ca được duyệt') where id=v_shift.id;
  update public.rumi_shift_change_requests set
    status='Đã duyệt', replacement_employee_id=p_replacement_employee_id,
    admin_note=coalesce(p_admin_note,''), reviewed_at=now()
  where id=p_request_id;
  return jsonb_build_object('shift_id',v_shift.id,'old_employee_id',v_old_employee,'new_employee_id',p_replacement_employee_id);
end;
$$;

-- --------------------------------------------------------------------------
-- Row-level isolation: browser roles never access RUMI tables directly.
-- The Python backend uses a secret/service-role key.
-- --------------------------------------------------------------------------
do $$
declare t text;
begin
  foreach t in array array[
    'rumi_employees','rumi_shifts','rumi_attendance','rumi_inventory','rumi_withdrawals',
    'rumi_purchase_requests','rumi_payroll_adjustments','rumi_payroll_payments','rumi_users',
    'rumi_locations','rumi_settings','rumi_availability_requests','rumi_leave_requests',
    'rumi_shift_change_requests','rumi_notifications','rumi_audit_logs'
  ] loop
    execute format('alter table public.%I enable row level security', t);
    execute format('revoke all on table public.%I from anon, authenticated', t);
  end loop;
end $$;

revoke execute on function public.rumi_restock_inventory(bigint,numeric) from public, anon, authenticated;
revoke execute on function public.rumi_withdraw_inventory(bigint,bigint,numeric,date,text) from public, anon, authenticated;
revoke execute on function public.rumi_clock_shift(bigint,bigint,text,double precision,double precision,double precision,timestamptz) from public, anon, authenticated;
revoke execute on function public.rumi_assign_replacement(bigint,bigint,text) from public, anon, authenticated;

commit;
