-- RUMI Manager 6.4 — Đăng ký ca theo tuần
-- Chỉ tạo/sửa các đối tượng có tiền tố rumi_. Có thể chạy nhiều lần.

begin;

create table if not exists public.rumi_weekly_shift_requests (
  id bigint generated by default as identity primary key,
  employee_id bigint not null references public.rumi_employees(id) on delete cascade,
  week_start date not null,
  location_id bigint not null references public.rumi_locations(id) on delete restrict,
  requested_day_off date,
  status text not null default 'Chờ duyệt'
    check (status in ('Chờ duyệt','Duyệt một phần','Đã duyệt','Từ chối','Đã rút')),
  employee_note text not null default '',
  admin_note text not null default '',
  selected_days integer not null default 0,
  selected_hours numeric(8,2) not null default 0,
  approved_days integer not null default 0,
  waitlist_days integer not null default 0,
  rejected_days integer not null default 0,
  submitted_at timestamptz not null default now(),
  reviewed_at timestamptz,
  reviewed_by bigint references public.rumi_users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(employee_id, week_start),
  constraint rumi_weekly_request_monday_check check (extract(isodow from week_start) = 1),
  constraint rumi_weekly_request_day_off_check check (
    requested_day_off is null or requested_day_off between week_start and week_start + 6
  )
);

create table if not exists public.rumi_weekly_shift_request_items (
  id bigint generated by default as identity primary key,
  request_id bigint not null references public.rumi_weekly_shift_requests(id) on delete cascade,
  opening_id bigint not null references public.rumi_shift_openings(id) on delete restrict,
  application_id bigint references public.rumi_shift_applications(id) on delete set null,
  shift_id bigint references public.rumi_shifts(id) on delete set null,
  work_date date not null,
  shift_code text not null check (shift_code in ('CA_09_17','CA_17_23')),
  start_time time without time zone not null,
  end_time time without time zone not null,
  status text not null default 'Chờ duyệt'
    check (status in ('Chờ duyệt','Đã duyệt','Danh sách chờ','Từ chối','Đã rút')),
  admin_note text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(request_id, work_date),
  unique(request_id, opening_id),
  constraint rumi_weekly_item_time_check check (
    (shift_code = 'CA_09_17' and start_time = time '09:00' and end_time = time '17:00')
    or
    (shift_code = 'CA_17_23' and start_time = time '17:00' and end_time = time '23:00')
  )
);

alter table public.rumi_shift_applications
  add column if not exists weekly_request_id bigint references public.rumi_weekly_shift_requests(id) on delete set null;

create index if not exists rumi_weekly_requests_week_status_idx
  on public.rumi_weekly_shift_requests(week_start, status, employee_id);
create index if not exists rumi_weekly_items_request_status_idx
  on public.rumi_weekly_shift_request_items(request_id, status, work_date);
create index if not exists rumi_weekly_items_opening_idx
  on public.rumi_weekly_shift_request_items(opening_id, status);
create index if not exists rumi_applications_weekly_request_idx
  on public.rumi_shift_applications(weekly_request_id, status);

alter table public.rumi_weekly_shift_requests enable row level security;
alter table public.rumi_weekly_shift_request_items enable row level security;
revoke all on table public.rumi_weekly_shift_requests from anon, authenticated;
revoke all on table public.rumi_weekly_shift_request_items from anon, authenticated;

create or replace function public.rumi_refresh_weekly_shift_request(p_request_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_total integer := 0;
  v_approved integer := 0;
  v_waitlist integer := 0;
  v_rejected integer := 0;
  v_withdrawn integer := 0;
  v_status text := 'Chờ duyệt';
  v_employee_id bigint;
  v_week_start date;
  v_employment_type text;
begin
  select employee_id, week_start
    into v_employee_id, v_week_start
  from public.rumi_weekly_shift_requests
  where id = p_request_id;

  if v_employee_id is null then
    return;
  end if;

  select
    count(*),
    count(*) filter (where status = 'Đã duyệt'),
    count(*) filter (where status = 'Danh sách chờ'),
    count(*) filter (where status = 'Từ chối'),
    count(*) filter (where status = 'Đã rút')
  into v_total, v_approved, v_waitlist, v_rejected, v_withdrawn
  from public.rumi_weekly_shift_request_items
  where request_id = p_request_id;

  if v_total > 0 and v_approved = v_total then
    v_status := 'Đã duyệt';
  elsif v_total > 0 and v_withdrawn = v_total then
    v_status := 'Đã rút';
  elsif v_total > 0 and v_rejected = v_total then
    v_status := 'Từ chối';
  elsif v_approved > 0 or v_waitlist > 0 or v_rejected > 0 then
    v_status := 'Duyệt một phần';
  else
    v_status := 'Chờ duyệt';
  end if;

  update public.rumi_weekly_shift_requests
  set status = v_status,
      approved_days = v_approved,
      waitlist_days = v_waitlist,
      rejected_days = v_rejected,
      reviewed_at = case when v_status <> 'Chờ duyệt' then coalesce(reviewed_at, now()) else reviewed_at end,
      updated_at = now()
  where id = p_request_id;

  if v_status = 'Đã duyệt' then
    select employment_type into v_employment_type
    from public.rumi_employees where id = v_employee_id;

    if v_employment_type = 'Full-time' then
      update public.rumi_weekly_day_off_requests
      set status = 'Đã duyệt',
          approved_date = preferred_date,
          reviewed_at = coalesce(reviewed_at, now()),
          admin_note = case when admin_note = '' then 'Duyệt cùng đơn đăng ký ca cả tuần' else admin_note end
      where employee_id = v_employee_id and week_start = v_week_start;
    end if;
  end if;
end;
$$;

create or replace function public.rumi_sync_weekly_request_from_application()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_shift_id bigint;
begin
  if new.weekly_request_id is null then
    return new;
  end if;

  select id into v_shift_id
  from public.rumi_shifts
  where application_id = new.id
  order by id desc
  limit 1;

  update public.rumi_weekly_shift_request_items
  set status = new.status,
      shift_id = coalesce(v_shift_id, shift_id),
      updated_at = now()
  where application_id = new.id;

  perform public.rumi_refresh_weekly_shift_request(new.weekly_request_id);
  return new;
end;
$$;

drop trigger if exists rumi_sync_weekly_request_application_trg on public.rumi_shift_applications;
create trigger rumi_sync_weekly_request_application_trg
after insert or update of status, weekly_request_id on public.rumi_shift_applications
for each row execute function public.rumi_sync_weekly_request_from_application();

create or replace function public.rumi_submit_weekly_shift_request(
  p_employee_id bigint,
  p_week_start date,
  p_location_id bigint,
  p_employee_note text,
  p_opening_ids bigint[]
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_employee public.rumi_employees%rowtype;
  v_request_id bigint;
  v_opening public.rumi_shift_openings%rowtype;
  v_application_id bigint;
  v_existing_status text;
  v_selected_days integer := coalesce(cardinality(p_opening_ids), 0);
  v_selected_hours numeric(8,2) := 0;
  v_seen_dates date[] := array[]::date[];
  v_requested_day_off date;
  v_approved_existing integer := 0;
  v_opening_id bigint;
begin
  if extract(isodow from p_week_start) <> 1 then
    raise exception 'Ngày đầu tuần phải là Thứ Hai';
  end if;

  select * into v_employee
  from public.rumi_employees
  where id = p_employee_id and status = 'Đang làm';

  if not found then
    raise exception 'Nhân viên không tồn tại hoặc đã ngừng hoạt động';
  end if;

  if v_employee.employment_type = 'Full-time' and v_selected_days <> 6 then
    raise exception 'Nhân viên Full-time phải chọn đúng 6 ngày làm và nghỉ 1 ngày';
  end if;
  if v_employee.employment_type <> 'Full-time' and v_selected_days < 1 then
    raise exception 'Hãy chọn ít nhất một ca trong tuần';
  end if;
  if v_selected_days > 7 then
    raise exception 'Mỗi ngày chỉ được đăng ký một ca';
  end if;
  if (select count(distinct x) from unnest(coalesce(p_opening_ids, array[]::bigint[])) as x) <> v_selected_days then
    raise exception 'Danh sách ca bị trùng';
  end if;

  select id into v_request_id
  from public.rumi_weekly_shift_requests
  where employee_id = p_employee_id and week_start = p_week_start
  for update;

  if v_request_id is not null then
    select count(*) into v_approved_existing
    from public.rumi_weekly_shift_request_items
    where request_id = v_request_id and status = 'Đã duyệt';
    if v_approved_existing > 0 then
      raise exception 'Đơn tuần đã được duyệt một phần. Hãy liên hệ quản lý để thay đổi lịch';
    end if;

    update public.rumi_shift_applications
    set status = 'Đã rút', reviewed_at = null, reviewed_by = null,
        admin_note = 'Nhân viên gửi lại đơn đăng ký cả tuần'
    where weekly_request_id = v_request_id
      and status in ('Chờ duyệt','Danh sách chờ','Từ chối','Đã rút');

    delete from public.rumi_weekly_shift_request_items where request_id = v_request_id;

    update public.rumi_weekly_shift_requests
    set location_id = p_location_id,
        status = 'Chờ duyệt',
        employee_note = coalesce(p_employee_note, ''),
        admin_note = '',
        approved_days = 0,
        waitlist_days = 0,
        rejected_days = 0,
        submitted_at = now(),
        reviewed_at = null,
        reviewed_by = null,
        updated_at = now()
    where id = v_request_id;
  else
    insert into public.rumi_weekly_shift_requests(
      employee_id, week_start, location_id, employee_note
    ) values (
      p_employee_id, p_week_start, p_location_id, coalesce(p_employee_note, '')
    ) returning id into v_request_id;
  end if;

  foreach v_opening_id in array coalesce(p_opening_ids, array[]::bigint[]) loop
    select * into v_opening
    from public.rumi_shift_openings
    where id = v_opening_id;

    if not found then
      raise exception 'Có ca đăng ký không tồn tại';
    end if;
    if v_opening.location_id <> p_location_id then
      raise exception 'Các ca trong một đơn tuần phải cùng cửa hàng';
    end if;
    if v_opening.work_date not between p_week_start and p_week_start + 6 then
      raise exception 'Ca đăng ký không nằm trong tuần đã chọn';
    end if;
    if v_opening.status <> 'Mở đăng ký' then
      raise exception 'Có ca không còn nhận đăng ký';
    end if;
    if v_opening.application_deadline is not null and v_opening.application_deadline < now() then
      raise exception 'Có ca đã hết hạn đăng ký';
    end if;
    if v_opening.eligible_employment_type <> 'Tất cả'
       and v_opening.eligible_employment_type <> v_employee.employment_type then
      raise exception 'Có ca không dành cho loại nhân viên của bạn';
    end if;
    if v_opening.work_date = any(v_seen_dates) then
      raise exception 'Mỗi ngày chỉ được chọn một ca';
    end if;
    v_seen_dates := array_append(v_seen_dates, v_opening.work_date);

    if v_opening.start_time = time '09:00' and v_opening.end_time = time '17:00' then
      null;
    elsif v_opening.start_time = time '17:00' and v_opening.end_time = time '23:00' then
      null;
    else
      raise exception 'Đơn tuần chỉ hỗ trợ ca 09:00–17:00 và 17:00–23:00';
    end if;

    select status into v_existing_status
    from public.rumi_shift_applications
    where opening_id = v_opening.id and employee_id = p_employee_id;

    if v_existing_status = 'Đã duyệt' then
      raise exception 'Bạn đã được duyệt vào một ca trong tuần này';
    end if;

    insert into public.rumi_shift_applications(
      opening_id, employee_id, weekly_request_id, status,
      employee_note, admin_note, score_snapshot, applied_at,
      reviewed_at, reviewed_by
    ) values (
      v_opening.id, p_employee_id, v_request_id, 'Chờ duyệt',
      coalesce(p_employee_note, ''), '', 0, now(), null, null
    )
    on conflict (opening_id, employee_id) do update
      set weekly_request_id = excluded.weekly_request_id,
          status = 'Chờ duyệt',
          employee_note = excluded.employee_note,
          admin_note = '',
          applied_at = now(),
          reviewed_at = null,
          reviewed_by = null
    returning id into v_application_id;

    insert into public.rumi_weekly_shift_request_items(
      request_id, opening_id, application_id, work_date,
      shift_code, start_time, end_time, status
    ) values (
      v_request_id, v_opening.id, v_application_id, v_opening.work_date,
      case when v_opening.start_time = time '09:00' then 'CA_09_17' else 'CA_17_23' end,
      v_opening.start_time, v_opening.end_time, 'Chờ duyệt'
    );

    v_selected_hours := v_selected_hours + extract(epoch from (v_opening.end_time - v_opening.start_time)) / 3600;
  end loop;

  if v_employee.employment_type = 'Full-time' then
    select d::date into v_requested_day_off
    from generate_series(p_week_start, p_week_start + 6, interval '1 day') as d
    where d::date <> all(v_seen_dates)
    order by d
    limit 1;

    insert into public.rumi_weekly_day_off_requests(
      employee_id, week_start, preferred_date, alternate_date,
      approved_date, reason, status, admin_note,
      reviewed_at, reviewed_by, created_at
    ) values (
      p_employee_id, p_week_start, v_requested_day_off, null,
      null, 'Ngày nghỉ theo đơn đăng ký ca cả tuần', 'Chờ duyệt', '',
      null, null, now()
    )
    on conflict (employee_id, week_start) do update
      set preferred_date = excluded.preferred_date,
          alternate_date = null,
          approved_date = null,
          reason = excluded.reason,
          status = 'Chờ duyệt',
          admin_note = '',
          reviewed_at = null,
          reviewed_by = null;
  else
    v_requested_day_off := null;
  end if;

  update public.rumi_weekly_shift_requests
  set requested_day_off = v_requested_day_off,
      selected_days = v_selected_days,
      selected_hours = round(v_selected_hours, 2),
      updated_at = now()
  where id = v_request_id;

  perform public.rumi_refresh_weekly_shift_request(v_request_id);

  return jsonb_build_object(
    'request_id', v_request_id,
    'selected_days', v_selected_days,
    'selected_hours', round(v_selected_hours, 2),
    'requested_day_off', v_requested_day_off,
    'status', 'Chờ duyệt'
  );
end;
$$;

commit;
