-- ============================================================================
-- RUMI Manager v5.4 SHIFT MARKET
-- Admin đăng ca -> nhân viên đăng ký -> admin duyệt/từ chối/danh sách chờ.
-- Hỗ trợ Full-time làm tối đa 6 ngày/tuần và đăng ký ngày nghỉ ưu tiên.
-- Chỉ tạo/sửa đối tượng rumi_ trong cùng Supabase với IC3 Smart Class.
-- Chạy SAU SQL v4 và v5.3.
-- ============================================================================

begin;

alter table public.rumi_employees
  add column if not exists employment_type text not null default 'Part-time';
alter table public.rumi_employees
  add column if not exists weekly_target_hours numeric(8,2) not null default 24;
alter table public.rumi_employees
  add column if not exists max_weekly_hours numeric(8,2) not null default 48;
alter table public.rumi_employees
  add column if not exists max_daily_hours numeric(8,2) not null default 8;
alter table public.rumi_employees
  add column if not exists max_consecutive_days integer not null default 6;
alter table public.rumi_employees
  add column if not exists weekly_days_off integer not null default 1;

alter table public.rumi_employees drop constraint if exists rumi_employees_employment_type_check;
alter table public.rumi_employees add constraint rumi_employees_employment_type_check
  check (employment_type in ('Full-time','Part-time'));
alter table public.rumi_employees drop constraint if exists rumi_employees_weekly_target_check;
alter table public.rumi_employees add constraint rumi_employees_weekly_target_check
  check (weekly_target_hours between 0 and 100 and max_weekly_hours between weekly_target_hours and 120);
alter table public.rumi_employees drop constraint if exists rumi_employees_daily_limit_check;
alter table public.rumi_employees add constraint rumi_employees_daily_limit_check
  check (max_daily_hours between 1 and 24 and max_consecutive_days between 1 and 7 and weekly_days_off between 0 and 6);

-- Giá trị hợp lý cho dữ liệu cũ.
update public.rumi_employees
set weekly_target_hours = case when employment_type = 'Full-time' then 48 else 24 end,
    max_weekly_hours = case when employment_type = 'Full-time' then greatest(max_weekly_hours,48) else greatest(max_weekly_hours,36) end,
    weekly_days_off = case when employment_type = 'Full-time' then greatest(weekly_days_off,1) else weekly_days_off end
where weekly_target_hours = 24 and max_weekly_hours = 48;

create table if not exists public.rumi_shift_openings (
  id bigint generated by default as identity primary key,
  location_id bigint not null references public.rumi_locations(id) on delete restrict,
  work_date date not null,
  start_time time without time zone not null,
  end_time time without time zone not null,
  required_role text not null default '',
  required_count integer not null default 1 check (required_count between 1 and 50),
  eligible_employment_type text not null default 'Tất cả'
    check (eligible_employment_type in ('Tất cả','Full-time','Part-time')),
  application_deadline timestamptz,
  note text not null default '',
  status text not null default 'Nháp'
    check (status in ('Nháp','Mở đăng ký','Đã đóng','Đã chốt','Đã hủy')),
  created_by bigint references public.rumi_users(id) on delete set null,
  published_at timestamptz,
  closed_at timestamptz,
  finalized_at timestamptz,
  created_at timestamptz not null default now(),
  constraint rumi_shift_openings_time_check check (end_time > start_time)
);

create table if not exists public.rumi_shift_applications (
  id bigint generated by default as identity primary key,
  opening_id bigint not null references public.rumi_shift_openings(id) on delete cascade,
  employee_id bigint not null references public.rumi_employees(id) on delete cascade,
  status text not null default 'Chờ duyệt'
    check (status in ('Chờ duyệt','Đã duyệt','Danh sách chờ','Từ chối','Đã rút')),
  employee_note text not null default '',
  admin_note text not null default '',
  score_snapshot numeric(8,2) not null default 0,
  applied_at timestamptz not null default now(),
  reviewed_at timestamptz,
  reviewed_by bigint references public.rumi_users(id) on delete set null,
  unique(opening_id, employee_id)
);

create table if not exists public.rumi_weekly_day_off_requests (
  id bigint generated by default as identity primary key,
  employee_id bigint not null references public.rumi_employees(id) on delete cascade,
  week_start date not null,
  preferred_date date not null,
  alternate_date date,
  approved_date date,
  reason text not null default '',
  status text not null default 'Chờ duyệt'
    check (status in ('Chờ duyệt','Đã duyệt','Từ chối')),
  admin_note text not null default '',
  reviewed_at timestamptz,
  reviewed_by bigint references public.rumi_users(id) on delete set null,
  created_at timestamptz not null default now(),
  unique(employee_id, week_start),
  constraint rumi_day_off_week_check check (
    preferred_date between week_start and week_start + 6
    and (alternate_date is null or alternate_date between week_start and week_start + 6)
    and (approved_date is null or approved_date between week_start and week_start + 6)
  )
);

alter table public.rumi_shifts
  add column if not exists opening_id bigint references public.rumi_shift_openings(id) on delete set null;
alter table public.rumi_shifts
  add column if not exists application_id bigint references public.rumi_shift_applications(id) on delete set null;

create unique index if not exists rumi_shift_application_assignment_unique
  on public.rumi_shifts(application_id) where application_id is not null;
create index if not exists rumi_openings_date_status_idx
  on public.rumi_shift_openings(work_date, status, start_time);
create index if not exists rumi_applications_opening_status_idx
  on public.rumi_shift_applications(opening_id, status, applied_at);
create index if not exists rumi_applications_employee_idx
  on public.rumi_shift_applications(employee_id, status, applied_at desc);
create index if not exists rumi_day_off_week_idx
  on public.rumi_weekly_day_off_requests(week_start, status, employee_id);
create index if not exists rumi_shifts_opening_idx
  on public.rumi_shifts(opening_id, status);

-- Kiểm tra ràng buộc ca ngay ở DB: không trùng, không nghỉ, không vượt giới hạn.
create or replace function public.rumi_validate_shift_assignment()
returns trigger
language plpgsql
set search_path = public
as $$
declare
  v_employee public.rumi_employees%rowtype;
  v_hours numeric(8,2);
  v_day_hours numeric(8,2);
  v_week_hours numeric(8,2);
  v_week_start date;
  v_distinct_days integer;
  v_capacity integer;
  v_required integer;
  v_day date;
  v_prev date;
  v_run integer := 0;
  v_max_run integer := 0;
begin
  if new.status not in ('Đã xếp','Đã xác nhận') then return new; end if;

  select * into v_employee from public.rumi_employees where id = new.employee_id;
  if not found or v_employee.status <> 'Đang làm' then
    raise exception 'Nhân viên không còn ở trạng thái đang làm';
  end if;

  if exists (
    select 1 from public.rumi_leave_requests l
    where l.employee_id = new.employee_id and l.status = 'Đã duyệt'
      and new.shift_date between l.start_date and l.end_date
  ) then raise exception 'Nhân viên đang nghỉ phép trong ngày này'; end if;

  if exists (
    select 1 from public.rumi_weekly_day_off_requests d
    where d.employee_id = new.employee_id and d.status = 'Đã duyệt'
      and d.approved_date = new.shift_date
  ) then raise exception 'Đây là ngày nghỉ tuần đã được duyệt của nhân viên'; end if;

  if exists (
    select 1 from public.rumi_shifts s
    where s.employee_id = new.employee_id and s.shift_date = new.shift_date
      and s.status in ('Đã xếp','Đã xác nhận')
      and (new.id is null or s.id <> new.id)
      and s.start_time < new.end_time and s.end_time > new.start_time
  ) then raise exception 'Nhân viên bị trùng ca trong khung giờ này'; end if;

  v_hours := round((extract(epoch from (new.end_time - new.start_time))/3600)::numeric,2);
  select coalesce(sum(extract(epoch from (s.end_time-s.start_time))/3600),0)
    into v_day_hours
  from public.rumi_shifts s
  where s.employee_id = new.employee_id and s.shift_date = new.shift_date
    and s.status in ('Đã xếp','Đã xác nhận') and (new.id is null or s.id <> new.id);
  if v_day_hours + v_hours > v_employee.max_daily_hours then
    raise exception 'Vượt giới hạn % giờ làm trong ngày', v_employee.max_daily_hours;
  end if;

  v_week_start := new.shift_date - extract(isodow from new.shift_date)::integer + 1;
  select coalesce(sum(extract(epoch from (s.end_time-s.start_time))/3600),0),
         count(distinct s.shift_date)
    into v_week_hours, v_distinct_days
  from public.rumi_shifts s
  where s.employee_id = new.employee_id
    and s.shift_date between v_week_start and v_week_start + 6
    and s.status in ('Đã xếp','Đã xác nhận') and (new.id is null or s.id <> new.id);
  if v_week_hours + v_hours > v_employee.max_weekly_hours then
    raise exception 'Vượt giới hạn % giờ làm trong tuần', v_employee.max_weekly_hours;
  end if;

  if not exists (
    select 1 from public.rumi_shifts s where s.employee_id = new.employee_id
      and s.shift_date = new.shift_date and s.status in ('Đã xếp','Đã xác nhận')
      and (new.id is null or s.id <> new.id)
  ) then v_distinct_days := v_distinct_days + 1; end if;
  if v_employee.employment_type = 'Full-time'
     and v_distinct_days > 7 - v_employee.weekly_days_off then
    raise exception 'Full-time phải nghỉ ít nhất % ngày trong tuần', v_employee.weekly_days_off;
  end if;

  for v_day in
    select distinct d from (
      select s.shift_date d from public.rumi_shifts s
      where s.employee_id = new.employee_id and s.status in ('Đã xếp','Đã xác nhận')
        and s.shift_date between new.shift_date - 7 and new.shift_date + 7
        and (new.id is null or s.id <> new.id)
      union select new.shift_date
    ) q order by d
  loop
    if v_prev is not null and v_day = v_prev + 1 then v_run := v_run + 1; else v_run := 1; end if;
    v_max_run := greatest(v_max_run, v_run); v_prev := v_day;
  end loop;
  if v_max_run > v_employee.max_consecutive_days then
    raise exception 'Vượt giới hạn % ngày làm liên tiếp', v_employee.max_consecutive_days;
  end if;

  if new.opening_id is not null then
    select required_count into v_required from public.rumi_shift_openings where id = new.opening_id;
    select count(*) into v_capacity from public.rumi_shifts s
      where s.opening_id = new.opening_id and s.status in ('Đã xếp','Đã xác nhận')
        and (new.id is null or s.id <> new.id);
    if v_capacity >= v_required then raise exception 'Ca đã đủ số nhân viên cần'; end if;
  end if;
  return new;
end;
$$;

drop trigger if exists rumi_shifts_validate_assignment on public.rumi_shifts;
create trigger rumi_shifts_validate_assignment
before insert or update of employee_id, shift_date, start_time, end_time, status, opening_id
on public.rumi_shifts
for each row execute function public.rumi_validate_shift_assignment();

alter table public.rumi_shift_openings enable row level security;
alter table public.rumi_shift_applications enable row level security;
alter table public.rumi_weekly_day_off_requests enable row level security;
revoke all on table public.rumi_shift_openings from anon, authenticated;
revoke all on table public.rumi_shift_applications from anon, authenticated;
revoke all on table public.rumi_weekly_day_off_requests from anon, authenticated;

commit;
