-- ============================================================================
-- RUMI Manager v6.4.2 ADMIN CONTROL
-- 1) Admin chọn/xóa nhiều thông báo.
-- 2) Xóa mềm lịch sử lấy nguyên liệu (không hoàn tồn kho).
-- 3) Giới hạn tuyệt đối 56 giờ/tuần.
-- 4) Đổi nhân viên cho ca đã xếp, chỉ sang người đã đăng ký đúng ca.
-- Chạy SAU SQL v6.4.1. Chỉ tạo/sửa đối tượng rumi_*.
-- ============================================================================

begin;

-- --------------------------------------------------------------------------
-- 56 giờ/tuần là trần hệ thống. Mục tiêu vẫn có thể thấp hơn.
-- --------------------------------------------------------------------------
alter table public.rumi_employees
  alter column max_weekly_hours set default 56;

alter table public.rumi_employees
  drop constraint if exists rumi_employees_weekly_target_check;

update public.rumi_employees
set weekly_target_hours = least(coalesce(weekly_target_hours, 0), 56),
    max_weekly_hours = case
      when coalesce(max_weekly_hours, 48) = 48 then 56
      else least(56, greatest(coalesce(max_weekly_hours, 56), least(coalesce(weekly_target_hours, 0), 56)))
    end;

alter table public.rumi_employees
  add constraint rumi_employees_weekly_target_check
  check (
    weekly_target_hours between 0 and 56
    and max_weekly_hours between weekly_target_hours and 56
  );

-- Không cho đơn đăng ký tuần vượt giới hạn cá nhân hoặc trần 56 giờ.
create or replace function public.rumi_validate_weekly_request_hours()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_employee_id bigint;
  v_limit numeric(8,2);
  v_existing numeric(10,2);
  v_new_hours numeric(10,2);
begin
  select r.employee_id, least(coalesce(e.max_weekly_hours, 56), 56)
    into v_employee_id, v_limit
  from public.rumi_weekly_shift_requests r
  join public.rumi_employees e on e.id = r.employee_id
  where r.id = new.request_id;

  if v_employee_id is null then
    raise exception 'Không tìm thấy đơn đăng ký tuần hoặc nhân viên';
  end if;

  select coalesce(sum(extract(epoch from (i.end_time - i.start_time))/3600), 0)
    into v_existing
  from public.rumi_weekly_shift_request_items i
  where i.request_id = new.request_id
    and (new.id is null or i.id <> new.id);

  v_new_hours := extract(epoch from (new.end_time - new.start_time))/3600;
  if v_existing + v_new_hours > v_limit + 0.001 then
    raise exception 'Đơn đăng ký vượt giới hạn % giờ làm trong tuần', v_limit;
  end if;

  return new;
end;
$$;

drop trigger if exists rumi_validate_weekly_request_hours_trg
  on public.rumi_weekly_shift_request_items;
create trigger rumi_validate_weekly_request_hours_trg
before insert or update of request_id, start_time, end_time
on public.rumi_weekly_shift_request_items
for each row execute function public.rumi_validate_weekly_request_hours();

-- --------------------------------------------------------------------------
-- Xóa mềm lịch sử lấy hàng: ẩn khỏi giao diện nhưng không cộng lại tồn kho.
-- --------------------------------------------------------------------------
alter table public.rumi_withdrawals
  add column if not exists deleted_at timestamptz;
alter table public.rumi_withdrawals
  add column if not exists deleted_by bigint references public.rumi_users(id) on delete set null;
alter table public.rumi_withdrawals
  add column if not exists delete_reason text not null default '';

create index if not exists rumi_withdrawals_active_history_idx
  on public.rumi_withdrawals(taken_at desc, id desc)
  where deleted_at is null;

-- --------------------------------------------------------------------------
-- Nhật ký đổi người cho ca đã xếp.
-- --------------------------------------------------------------------------
create table if not exists public.rumi_shift_reassignments (
  id bigint generated by default as identity primary key,
  shift_id bigint not null references public.rumi_shifts(id) on delete restrict,
  opening_id bigint references public.rumi_shift_openings(id) on delete set null,
  old_employee_id bigint references public.rumi_employees(id) on delete set null,
  new_employee_id bigint not null references public.rumi_employees(id) on delete restrict,
  old_application_id bigint references public.rumi_shift_applications(id) on delete set null,
  new_application_id bigint not null references public.rumi_shift_applications(id) on delete restrict,
  changed_by bigint references public.rumi_users(id) on delete set null,
  note text not null default '',
  changed_at timestamptz not null default now()
);

create index if not exists rumi_shift_reassignments_shift_idx
  on public.rumi_shift_reassignments(shift_id, changed_at desc);

alter table public.rumi_shift_reassignments enable row level security;
revoke all on table public.rumi_shift_reassignments from anon, authenticated;

create or replace function public.rumi_reassign_shift_to_application(
  p_shift_id bigint,
  p_application_id bigint,
  p_admin_user_id bigint,
  p_note text default ''
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_shift public.rumi_shifts%rowtype;
  v_application public.rumi_shift_applications%rowtype;
  v_old_employee_id bigint;
  v_old_application_id bigint;
  v_old_weekly_request_id bigint;
  v_new_weekly_request_id bigint;
begin
  select * into v_shift
  from public.rumi_shifts
  where id = p_shift_id
  for update;

  if not found then raise exception 'Không tìm thấy ca làm'; end if;
  if v_shift.opening_id is null then
    raise exception 'Ca này không được tạo từ đơn đăng ký';
  end if;
  if v_shift.shift_date < (now() at time zone 'Asia/Ho_Chi_Minh')::date then
    raise exception 'Không thể đổi nhân viên cho ca đã qua';
  end if;
  if exists (select 1 from public.rumi_attendance where shift_id = p_shift_id) then
    raise exception 'Ca đã có chấm công nên không thể đổi nhân viên';
  end if;

  select * into v_application
  from public.rumi_shift_applications
  where id = p_application_id
  for update;

  if not found then raise exception 'Không tìm thấy đơn đăng ký của nhân viên thay'; end if;
  if v_application.opening_id <> v_shift.opening_id then
    raise exception 'Nhân viên chưa đăng ký đúng lịch này';
  end if;
  if v_application.status not in ('Chờ duyệt','Danh sách chờ','Từ chối') then
    raise exception 'Đơn đăng ký không còn ở trạng thái có thể thay';
  end if;
  if v_application.employee_id = v_shift.employee_id then
    raise exception 'Nhân viên này đang được xếp trong ca';
  end if;
  if not exists (
    select 1 from public.rumi_employees
    where id = v_application.employee_id and status = 'Đang làm'
  ) then
    raise exception 'Nhân viên thay không còn hoạt động';
  end if;

  v_old_employee_id := v_shift.employee_id;
  v_old_application_id := v_shift.application_id;
  select weekly_request_id into v_old_weekly_request_id
  from public.rumi_shift_applications where id = v_old_application_id;
  v_new_weekly_request_id := v_application.weekly_request_id;

  -- Trigger kiểm tra ca của RUMI tiếp tục chặn trùng lịch, quá giờ/ngày,
  -- quá 56 giờ/tuần, nghỉ phép và ngày nghỉ Full-time.
  update public.rumi_shifts
  set employee_id = v_application.employee_id,
      application_id = v_application.id,
      note = concat_ws(' · ', nullif(note,''), 'Admin đổi nhân viên theo đơn đăng ký')
  where id = p_shift_id;

  if v_old_application_id is not null then
    update public.rumi_shift_applications
    set status = 'Danh sách chờ',
        admin_note = concat_ws(' · ', nullif(admin_note,''), 'Đã đổi sang nhân viên khác'),
        reviewed_at = now(), reviewed_by = p_admin_user_id
    where id = v_old_application_id;

    update public.rumi_weekly_shift_request_items
    set status = 'Danh sách chờ', shift_id = null, updated_at = now()
    where application_id = v_old_application_id;
  end if;

  update public.rumi_shift_applications
  set status = 'Đã duyệt',
      admin_note = concat_ws(' · ', nullif(admin_note,''), coalesce(nullif(p_note,''), 'Admin đổi vào ca đã xếp')),
      reviewed_at = now(), reviewed_by = p_admin_user_id
  where id = v_application.id;

  update public.rumi_weekly_shift_request_items
  set status = 'Đã duyệt', shift_id = p_shift_id, updated_at = now()
  where application_id = v_application.id;

  if v_old_weekly_request_id is not null then
    perform public.rumi_refresh_weekly_shift_request(v_old_weekly_request_id);
    -- Nếu Full-time mất một ngày đã duyệt sau khi đổi người, ngày nghỉ phải
    -- quay lại trạng thái chờ để admin xử lý lịch còn thiếu.
    update public.rumi_weekly_day_off_requests d
    set status = 'Chờ duyệt', approved_date = null,
        admin_note = concat_ws(' · ', nullif(d.admin_note,''), 'Lịch thay đổi sau khi đổi nhân viên'),
        reviewed_at = null, reviewed_by = null
    from public.rumi_weekly_shift_requests r
    join public.rumi_employees e on e.id = r.employee_id
    where r.id = v_old_weekly_request_id
      and d.employee_id = r.employee_id and d.week_start = r.week_start
      and e.employment_type = 'Full-time' and coalesce(r.approved_days,0) < 6;
  end if;
  if v_new_weekly_request_id is not null then
    perform public.rumi_refresh_weekly_shift_request(v_new_weekly_request_id);
  end if;

  insert into public.rumi_shift_reassignments(
    shift_id, opening_id, old_employee_id, new_employee_id,
    old_application_id, new_application_id, changed_by, note
  ) values (
    p_shift_id, v_shift.opening_id, v_old_employee_id, v_application.employee_id,
    v_old_application_id, v_application.id, p_admin_user_id, coalesce(p_note,'')
  );

  return jsonb_build_object(
    'shift_id', p_shift_id,
    'old_employee_id', v_old_employee_id,
    'new_employee_id', v_application.employee_id,
    'old_application_id', v_old_application_id,
    'new_application_id', v_application.id
  );
end;
$$;

revoke execute on function public.rumi_reassign_shift_to_application(bigint,bigint,bigint,text)
  from public, anon, authenticated;

commit;
