-- ============================================================================
-- RUMI Manager v5.3 OPERATIONS
-- Xếp lịch logic, chấm công chi tiết và bảng lương tháng có trạng thái chốt.
-- Chỉ tạo/sửa các đối tượng có tiền tố rumi_, không đụng dữ liệu IC3 Smart Class.
-- Chạy file này SAU SUPABASE_RUMI_V4_FULL.sql.
-- ============================================================================

begin;

-- Chi tiết giờ công dùng để tính lương minh bạch.
alter table public.rumi_attendance add column if not exists scheduled_hours numeric(8,2) not null default 0;
alter table public.rumi_attendance add column if not exists payable_hours numeric(8,2) not null default 0;
alter table public.rumi_attendance add column if not exists late_minutes integer not null default 0;
alter table public.rumi_attendance add column if not exists early_leave_minutes integer not null default 0;
alter table public.rumi_attendance add column if not exists overtime_minutes integer not null default 0;
alter table public.rumi_attendance add column if not exists calculation_note text not null default '';

-- Một kỳ lương theo tháng. Bản nháp có thể tính lại; bản đã chốt giữ số liệu ổn định.
create table if not exists public.rumi_payroll_runs (
  id bigint generated by default as identity primary key,
  month text not null unique check (month ~ '^\d{4}-\d{2}$'),
  status text not null default 'Nháp' check (status in ('Nháp','Đã chốt')),
  generated_at timestamptz not null default now(),
  locked_at timestamptz,
  generated_by bigint references public.rumi_users(id) on delete set null,
  note text not null default '',
  total_hours numeric(12,2) not null default 0,
  total_amount numeric(16,2) not null default 0,
  employee_count integer not null default 0
);

create table if not exists public.rumi_payroll_items (
  id bigint generated by default as identity primary key,
  run_id bigint not null references public.rumi_payroll_runs(id) on delete cascade,
  employee_id bigint not null references public.rumi_employees(id) on delete cascade,
  employee_code text not null default '',
  employee_name text not null,
  employee_role text not null default '',
  attendance_count integer not null default 0,
  hourly_wage numeric(14,2) not null default 0,
  scheduled_hours numeric(10,2) not null default 0,
  actual_hours numeric(10,2) not null default 0,
  payable_hours numeric(10,2) not null default 0,
  late_minutes integer not null default 0,
  early_leave_minutes integer not null default 0,
  overtime_minutes integer not null default 0,
  base_salary numeric(16,2) not null default 0,
  bonus numeric(16,2) not null default 0,
  penalty numeric(16,2) not null default 0,
  advance_pay numeric(16,2) not null default 0,
  total numeric(16,2) not null default 0,
  note text not null default '',
  created_at timestamptz not null default now(),
  unique (run_id, employee_id)
);

alter table public.rumi_payroll_items add column if not exists attendance_count integer not null default 0;

create index if not exists rumi_shifts_date_employee_idx on public.rumi_shifts(shift_date, employee_id);
create index if not exists rumi_attendance_work_employee_idx on public.rumi_attendance(work_date, employee_id);
create index if not exists rumi_availability_date_employee_idx on public.rumi_availability_requests(work_date, employee_id, status);
create index if not exists rumi_leave_employee_dates_idx on public.rumi_leave_requests(employee_id, start_date, end_date, status);
create index if not exists rumi_payroll_items_run_idx on public.rumi_payroll_items(run_id, employee_id);

-- Chặn xếp trùng ca hoặc xếp nhân viên đang nghỉ ngay ở cơ sở dữ liệu.
create or replace function public.rumi_validate_shift_assignment()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if new.status in ('Đã xếp','Đã xác nhận') then
    if not exists (select 1 from public.rumi_employees e where e.id = new.employee_id and e.status = 'Đang làm') then
      raise exception 'Nhân viên không còn ở trạng thái đang làm';
    end if;
    if exists (
      select 1 from public.rumi_leave_requests l
      where l.employee_id = new.employee_id and l.status = 'Đã duyệt'
        and new.shift_date between l.start_date and l.end_date
    ) then
      raise exception 'Nhân viên đang nghỉ phép trong ngày này';
    end if;
    if exists (
      select 1 from public.rumi_shifts s
      where s.employee_id = new.employee_id and s.shift_date = new.shift_date
        and s.status in ('Đã xếp','Đã xác nhận')
        and (new.id is null or s.id <> new.id)
        and s.start_time < new.end_time and s.end_time > new.start_time
    ) then
      raise exception 'Nhân viên bị trùng ca trong khung giờ này';
    end if;
  end if;
  return new;
end;
$$;

drop trigger if exists rumi_shifts_validate_assignment on public.rumi_shifts;
create trigger rumi_shifts_validate_assignment
before insert or update of employee_id, shift_date, start_time, end_time, status
on public.rumi_shifts
for each row execute function public.rumi_validate_shift_assignment();

-- Điền số liệu hợp lý cho dữ liệu chấm công cũ.
update public.rumi_attendance a
set
  scheduled_hours = round((extract(epoch from (s.end_time - s.start_time)) / 3600)::numeric, 2),
  payable_hours = case when a.hours > 0 then a.hours else 0 end,
  late_minutes = greatest(round(extract(epoch from (a.check_in - s.start_time)) / 60)::integer, 0),
  early_leave_minutes = case when a.check_out is null then 0 else greatest(round(extract(epoch from (s.end_time - a.check_out)) / 60)::integer, 0) end,
  overtime_minutes = case when a.check_out is null then 0 else greatest(round(extract(epoch from (a.check_out - s.end_time)) / 60)::integer, 0) end,
  calculation_note = case when a.note <> '' then a.note else 'Dữ liệu cũ được chuẩn hóa khi nâng cấp v5.3' end
from public.rumi_shifts s
where a.shift_id = s.id
  and (a.scheduled_hours = 0 or a.payable_hours = 0);

-- Chấm công GPS và tính chỉ số giờ công trong cùng một giao dịch.
create or replace function public.rumi_clock_shift(
  p_shift_id bigint,
  p_employee_id bigint,
  p_action text,
  p_lat double precision,
  p_lng double precision,
  p_accuracy double precision,
  p_now timestamptz default now()
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_shift public.rumi_shifts%rowtype;
  v_location public.rumi_locations%rowtype;
  v_settings public.rumi_settings%rowtype;
  v_attendance public.rumi_attendance%rowtype;
  v_shift_start timestamptz;
  v_shift_end timestamptz;
  v_distance double precision;
  v_action text;
  v_scheduled_hours numeric(8,2);
  v_actual_hours numeric(8,2);
  v_late_minutes integer;
  v_early_minutes integer;
  v_overtime_minutes integer;
  v_final_status text;
begin
  if p_lat is null or p_lng is null then raise exception 'Không nhận được vị trí GPS'; end if;
  select * into v_settings from public.rumi_settings where id = 1;
  select * into v_shift from public.rumi_shifts where id = p_shift_id for update;
  if not found then raise exception 'Không tìm thấy ca làm'; end if;
  if v_shift.employee_id <> p_employee_id then raise exception 'Ca làm không thuộc tài khoản này'; end if;
  if v_shift.status not in ('Đã xếp','Đã xác nhận') then raise exception 'Ca làm không ở trạng thái có thể chấm công'; end if;
  if v_shift.location_id is null then raise exception 'Ca làm chưa được cấu hình vị trí cửa hàng'; end if;

  select * into v_location from public.rumi_locations where id = v_shift.location_id and active = true;
  if not found then raise exception 'Vị trí cửa hàng không tồn tại hoặc đã tắt'; end if;

  if p_accuracy is null or p_accuracy > v_settings.max_gps_accuracy_m then
    raise exception 'GPS chưa đủ chính xác. Sai số hiện tại % m, tối đa % m', round(coalesce(p_accuracy,9999)::numeric,0), v_settings.max_gps_accuracy_m;
  end if;

  v_distance := 6371000 * 2 * asin(sqrt(
    power(sin(radians(p_lat - v_location.latitude) / 2), 2) +
    cos(radians(v_location.latitude)) * cos(radians(p_lat)) *
    power(sin(radians(p_lng - v_location.longitude) / 2), 2)
  ));
  if v_distance > v_location.radius_m then
    raise exception 'Bạn đang cách cửa hàng % m, phạm vi cho phép % m', round(v_distance::numeric,0), v_location.radius_m;
  end if;

  v_shift_start := (v_shift.shift_date + v_shift.start_time) at time zone v_settings.timezone;
  v_shift_end := (v_shift.shift_date + v_shift.end_time) at time zone v_settings.timezone;
  v_scheduled_hours := round((extract(epoch from (v_shift_end - v_shift_start)) / 3600)::numeric, 2);

  select * into v_attendance from public.rumi_attendance where shift_id = p_shift_id for update;
  v_action := lower(coalesce(p_action,'auto'));
  if v_action = 'auto' then
    v_action := case when found and v_attendance.check_out_at is null then 'checkout' else 'checkin' end;
  end if;

  if v_action = 'checkin' then
    if found then raise exception 'Ca này đã chấm công vào'; end if;
    if p_now < v_shift_start - make_interval(mins => v_settings.checkin_before_minutes)
       or p_now > v_shift_start + make_interval(mins => v_settings.checkin_after_minutes) then
      raise exception 'Chỉ được chấm công vào từ % đến %',
        to_char(v_shift_start - make_interval(mins => v_settings.checkin_before_minutes),'HH24:MI'),
        to_char(v_shift_start + make_interval(mins => v_settings.checkin_after_minutes),'HH24:MI');
    end if;
    v_late_minutes := greatest(round(extract(epoch from (p_now - v_shift_start)) / 60)::integer, 0);
    insert into public.rumi_attendance(
      shift_id, employee_id, work_date, check_in, check_in_at,
      check_in_lat, check_in_lng, check_in_accuracy_m, check_in_distance_m,
      scheduled_hours, payable_hours, late_minutes, early_leave_minutes, overtime_minutes,
      status, note, calculation_note
    ) values (
      p_shift_id, p_employee_id, v_shift.shift_date, (p_now at time zone v_settings.timezone)::time,
      p_now, p_lat, p_lng, p_accuracy, v_distance,
      v_scheduled_hours, 0, v_late_minutes, 0, 0,
      'Đang làm', '', case when v_late_minutes > 0 then concat('Vào trễ ',v_late_minutes,' phút') else 'Vào ca đúng giờ' end
    ) returning * into v_attendance;
    return jsonb_build_object(
      'action','checkin','time',to_char(p_now at time zone v_settings.timezone,'HH24:MI'),
      'distance_m',round(v_distance::numeric,1),'late_minutes',v_late_minutes,
      'scheduled_hours',v_scheduled_hours
    );
  end if;

  if v_action = 'checkout' then
    if not found then raise exception 'Bạn chưa chấm công vào ca này'; end if;
    if v_attendance.check_out_at is not null then raise exception 'Ca này đã chấm công ra'; end if;
    if p_now < v_shift_end - make_interval(mins => v_settings.checkout_before_minutes)
       or p_now > v_shift_end + make_interval(mins => v_settings.checkout_after_minutes) then
      raise exception 'Chỉ được chấm công ra từ % đến %',
        to_char(v_shift_end - make_interval(mins => v_settings.checkout_before_minutes),'HH24:MI'),
        to_char(v_shift_end + make_interval(mins => v_settings.checkout_after_minutes),'HH24:MI');
    end if;

    v_actual_hours := round(greatest(extract(epoch from (p_now - v_attendance.check_in_at)),0)::numeric / 3600, 2);
    v_late_minutes := greatest(round(extract(epoch from (v_attendance.check_in_at - v_shift_start)) / 60)::integer, 0);
    v_early_minutes := greatest(round(extract(epoch from (v_shift_end - p_now)) / 60)::integer, 0);
    v_overtime_minutes := greatest(round(extract(epoch from (p_now - v_shift_end)) / 60)::integer, 0);
    v_final_status := case
      when v_late_minutes > 0 and v_early_minutes > 0 then 'Đi trễ & về sớm'
      when v_late_minutes > 0 then 'Đi trễ'
      when v_early_minutes > 0 then 'Về sớm'
      when v_overtime_minutes > 0 then 'Có tăng ca'
      else 'Hoàn thành'
    end;

    update public.rumi_attendance set
      check_out = (p_now at time zone v_settings.timezone)::time,
      check_out_at = p_now,
      check_out_lat = p_lat,
      check_out_lng = p_lng,
      check_out_accuracy_m = p_accuracy,
      check_out_distance_m = v_distance,
      hours = v_actual_hours,
      payable_hours = v_actual_hours,
      scheduled_hours = v_scheduled_hours,
      late_minutes = v_late_minutes,
      early_leave_minutes = v_early_minutes,
      overtime_minutes = v_overtime_minutes,
      status = v_final_status,
      calculation_note = concat_ws(' · ',
        case when v_late_minutes > 0 then concat('Trễ ',v_late_minutes,' phút') end,
        case when v_early_minutes > 0 then concat('Về sớm ',v_early_minutes,' phút') end,
        case when v_overtime_minutes > 0 then concat('Tăng ca ',v_overtime_minutes,' phút') end,
        concat('Giờ tính lương ',v_actual_hours)
      )
    where id = v_attendance.id;

    return jsonb_build_object(
      'action','checkout','time',to_char(p_now at time zone v_settings.timezone,'HH24:MI'),
      'hours',v_actual_hours,'payable_hours',v_actual_hours,'distance_m',round(v_distance::numeric,1),
      'late_minutes',v_late_minutes,'early_leave_minutes',v_early_minutes,
      'overtime_minutes',v_overtime_minutes,'status',v_final_status
    );
  end if;

  raise exception 'Hành động chấm công không hợp lệ';
end;
$$;

-- Tách quyền truy cập: frontend không gọi trực tiếp các bảng mới.
alter table public.rumi_payroll_runs enable row level security;
alter table public.rumi_payroll_items enable row level security;
revoke all on table public.rumi_payroll_runs from anon, authenticated;
revoke all on table public.rumi_payroll_items from anon, authenticated;
revoke execute on function public.rumi_clock_shift(bigint,bigint,text,double precision,double precision,double precision,timestamptz) from public, anon, authenticated;

commit;
